import type React from "react";

export const database = {
  databaseRoot: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "284px minmax(0, 1fr)",
    gridTemplateRows: "40px minmax(0, 1fr)",
    background: "var(--bg-panel)",
    color: "var(--text-primary)",
  },
  databaseTopToolbar: {
    gridColumn: "1 / -1",
    height: 40,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: "0 8px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
  },
  databaseToolbarButton: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  databaseSidebar: {
    width: 284,
    gridColumn: "1",
    gridRow: "2",
    flexShrink: 0,
    position: "relative" as const,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    minHeight: 0,
  },
  databaseSidebarResizeHandle: {
    position: "absolute" as const,
    top: 0,
    right: -4,
    bottom: 0,
    zIndex: 4,
    width: 8,
    padding: 0,
    border: "none",
    borderRight: "1px solid transparent",
    background: "transparent",
    cursor: "col-resize",
  },
  databaseSidebarResizeHandleActive: {
    borderRightColor: "var(--accent)",
    background: "color-mix(in srgb, var(--accent) 14%, transparent)",
  },
  databaseSidebarHeader: {
    padding: "12px 12px 10px",
    borderBottom: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  databaseTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  databaseTitle: {
    fontSize: 13,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  databaseActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 6,
  },
  databaseSmallButton: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "0 10px",
    border: "1px solid var(--border-medium)",
    borderRadius: 10,
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12.8,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  databaseIconButton: {
    width: 32,
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  databaseDialogOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 3000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.28)",
  },
  databaseDialog: {
    width: 420,
    maxWidth: "calc(100vw - 32px)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-panel)",
    boxShadow: "0 18px 48px rgba(0, 0, 0, 0.22)",
    color: "var(--text-primary)",
  },
  databaseConnectionDialog: {
    width: 760,
    maxWidth: "calc(100vw - 32px)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-panel)",
    boxShadow: "0 18px 48px rgba(0, 0, 0, 0.22)",
    color: "var(--text-primary)",
  },
  databaseDialogHeader: {
    padding: "14px 16px 10px",
    borderBottom: "1px solid var(--border-dim)",
    fontSize: 13,
    fontWeight: 750,
  },
  databaseDialogBody: {
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  databaseDialogIntro: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  },
  databaseTypeChooserHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  databaseTypeViewToggle: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    padding: 2,
    border: "1px solid var(--border-dim)",
    borderRadius: 7,
    background: "var(--bg-subtle)",
  },
  databaseTypeViewButton: {
    height: 22,
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-muted)",
    padding: "0 8px",
    cursor: "pointer",
    fontSize: 11.5,
    fontWeight: 650,
  },
  databaseTypeViewButtonActive: {
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    boxShadow: "0 1px 2px rgba(0,0,0,0.12)",
  },
  databaseTypeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 10,
    maxHeight: "58vh",
    overflowY: "auto",
  },
  databaseTypeCard: {
    minHeight: 92,
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
  },
  databaseTypeCardSelected: {
    borderColor: "var(--border-focus)",
    background: "var(--accent-subtle)",
    color: "var(--text-primary)",
    boxShadow: "0 0 0 1px var(--border-focus)",
  },
  databaseTypeIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 800,
  },
  databaseTypeIconSmall: {
    width: 24,
    height: 24,
    borderRadius: 6,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    fontWeight: 800,
  },
  databaseTypeLabel: {
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12.5,
    fontWeight: 650,
  },
  databaseTypeList: {
    display: "grid",
    gap: 6,
    maxHeight: "58vh",
    overflowY: "auto",
  },
  databaseTypeListItem: {
    minHeight: 42,
    display: "grid",
    gridTemplateColumns: "24px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 10,
    border: "1px solid var(--border-dim)",
    borderRadius: 7,
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    padding: "0 10px",
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
  },
  databaseTypeMeta: {
    color: "var(--text-hint)",
    fontSize: 11.5,
    whiteSpace: "nowrap" as const,
  },
  databaseConfigHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  databaseTypeMiniCard: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    padding: "0 9px",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 650,
  },
  databaseConfigTabs: {
    display: "flex",
    gap: 4,
    borderBottom: "1px solid var(--border-dim)",
    paddingBottom: 8,
  },
  databaseConfigTab: {
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 9px",
    border: "1px solid transparent",
    borderRadius: 7,
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 650,
  },
  databaseConfigTabActive: {
    borderColor: "var(--border-medium)",
    background: "var(--bg-selected)",
    color: "var(--text-primary)",
  },
  databaseDialogFormGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
  },
  databaseInputButtonRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  databaseColorPickerRow: {
    minHeight: 34,
    display: "flex",
    alignItems: "center",
    gap: 7,
    flexWrap: "wrap" as const,
  },
  databaseColorSwatch: {
    width: 24,
    height: 24,
    border: "1px solid var(--border-medium)",
    borderRadius: 999,
    cursor: "pointer",
    padding: 0,
    flex: "0 0 auto",
  },
  databaseColorSwatchEmpty: {
    background: "transparent",
    borderStyle: "dashed",
  },
  databaseColorSwatchSelected: {
    boxShadow: "0 0 0 2px var(--bg-card), 0 0 0 4px var(--border-focus)",
  },
  databaseColorCustom: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-muted)",
    fontSize: 11.5,
    fontWeight: 650,
  },
  databaseDialogPanel: {
    minHeight: 160,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
    padding: 14,
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
  },
  databaseSwitchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--text-secondary)",
  },
  databaseDialogHint: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-muted)",
  },
  databaseDialogField: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  databaseDialogLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    color: "var(--text-muted)",
  },
  databaseDialogInput: {
    height: 32,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    padding: "0 9px",
    outline: "none",
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
  },
  databaseDialogFooter: {
    padding: "10px 16px 14px",
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
  databaseWorkspacePanel: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 16,
    overflow: "auto",
  },
  databaseWorkspaceHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  databaseWorkspaceTitle: {
    fontSize: 14,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  databaseSqlPreview: {
    flex: 1,
    minHeight: 220,
    margin: 0,
    padding: 12,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    overflow: "auto",
    whiteSpace: "pre-wrap" as const,
  },
  databaseSection: {
    padding: "10px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  databaseSectionTitle: {
    padding: "0 6px 3px",
    fontSize: 10.5,
    fontWeight: 750,
    color: "var(--text-hint)",
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
  },
  databaseScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  databaseListButton: {
    width: "100%",
    minHeight: 28,
    padding: "4px 8px",
    border: "1px solid transparent",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "center",
    gap: 6,
    textAlign: "left" as const,
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    transition: "all 0.15s ease",
  },
  databaseListButtonActive: {
    background: "var(--bg-selected)",
    borderColor: "var(--border-medium)",
    color: "var(--text-primary)",
  },
  databaseTreeChevron: {
    width: 12,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-hint)",
  },
  databaseConnectionNameBadge: {
    width: 22,
    height: 22,
    boxSizing: "border-box" as const,
    borderRadius: 7,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
    fontFamily: "var(--font-ui)",
    fontWeight: 800,
    lineHeight: 1,
    textAlign: "center" as const,
    letterSpacing: 0,
    userSelect: "none" as const,
  },
  databaseMain: {
    gridColumn: "2",
    gridRow: "2",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  databaseTopbar: {
    minHeight: 50,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  databasePath: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12,
    color: "var(--text-muted)",
  },
  databaseSqlPanel: {
    flexShrink: 0,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border-dim)",
    display: "flex",
    gap: 8,
    alignItems: "stretch",
  },
  databaseSqlInput: {
    flex: 1,
    minHeight: 68,
    maxHeight: 120,
    resize: "vertical" as const,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    padding: "8px 10px",
    outline: "none",
  },
  databaseToolbar: {
    height: 42,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  databaseGridFilterBar: {
    flexShrink: 0,
    display: "flex",
    alignItems: "end",
    gap: 8,
    padding: "8px 14px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    flexWrap: "wrap" as const,
  },
  databaseToolbarMenuAnchor: {
    position: "relative" as const,
    display: "inline-flex",
  },
  databaseToolbarMenu: {
    position: "absolute" as const,
    top: "calc(100% + 6px)",
    right: 0,
    zIndex: 20,
    minWidth: 220,
    maxWidth: 320,
    padding: 8,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-card)",
    boxShadow: "0 10px 30px rgba(0, 0, 0, 0.22)",
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  },
  databaseToolbarMenuWide: {
    width: 300,
  },
  databaseToolbarMenuButton: {
    width: "100%",
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    border: "1px solid transparent",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
    padding: "0 8px",
    fontSize: 12,
    fontFamily: "var(--font-ui)",
    textAlign: "left" as const,
  },
  databaseFieldFilterList: {
    maxHeight: 220,
    overflow: "auto",
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
    padding: "2px 0",
  },
  databaseFieldFilterItem: {
    minHeight: 28,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 6px",
    borderRadius: 6,
    color: "var(--text-primary)",
    fontSize: 12,
  },
  databaseFieldFilterFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 6,
    paddingTop: 4,
    borderTop: "1px solid var(--border-dim)",
  },
  databaseTableInfoRoot: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  databaseTableInfoHeader: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "10px 12px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  databaseTableInfoTabs: {
    flexShrink: 0,
    display: "grid",
    gridTemplateColumns: "repeat(5, minmax(0, 1fr))",
    borderBottom: "1px solid var(--border-medium)",
    background: "var(--bg-subtle)",
  },
  databaseTableInfoTab: {
    height: 36,
    border: 0,
    borderRight: "1px solid var(--border-medium)",
    borderBottomWidth: 2,
    borderBottomStyle: "solid" as const,
    borderBottomColor: "transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  databaseTableInfoTabActive: {
    background: "var(--bg-panel)",
    color: "var(--text-primary)",
    borderBottomColor: "var(--accent)",
  },
  databaseTableInfoSearch: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border-medium)",
    background: "var(--bg-panel)",
  },
  databaseTableInfoContent: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    background: "var(--bg-panel)",
  },
  databaseTableWrap: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    background: "var(--bg-panel)",
  },
  databaseTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    tableLayout: "fixed" as const,
    fontSize: 12,
  },
  databaseTh: {
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
    height: 58,
    padding: "4px 8px",
    borderBottom: "1px solid var(--border-medium)",
    borderRight: "1px solid var(--border-medium)",
    background: "var(--bg-sidebar)",
    color: "var(--text-secondary)",
    fontWeight: 700,
    textAlign: "left" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseGridHeaderText: {
    minWidth: 0,
    flex: "1 1 auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    overflow: "hidden",
  },
  databaseGridHeaderButton: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 30px",
    alignItems: "center",
    gap: 8,
    width: "100%",
    minHeight: 50,
    padding: 0,
    border: "none",
    background: "transparent",
    color: "inherit",
    font: "inherit",
    cursor: "pointer",
    overflow: "hidden",
  },
  databaseGridHeaderSortIcon: {
    width: 30,
    height: 24,
    minWidth: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    border: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    color: "var(--text-secondary)",
    flexShrink: 0,
  },
  databaseGridHeaderStack: {
    minWidth: 0,
    flex: "1 1 auto",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 2,
    overflow: "hidden",
    lineHeight: 1.2,
    textAlign: "left" as const,
    fontFamily: "Monaco, Menlo, Consolas, var(--font-mono)",
    fontWeight: 800,
  },
  databaseGridHeaderName: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 800,
    fontFamily: "Monaco, Menlo, Consolas, var(--font-mono)",
  },
  databaseGridHeaderTypeLine: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    color: "var(--text-hint)",
    fontSize: 11,
    fontWeight: 800,
    fontFamily: "Monaco, Menlo, Consolas, var(--font-mono)",
  },
  databaseGridHeaderCommentLine: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    color: "var(--text-hint)",
    fontSize: 10,
    fontWeight: 600,
    fontFamily: "Monaco, Menlo, Consolas, var(--font-mono)",
  },
  databaseGridRowSelected: {
    background: "color-mix(in srgb, var(--accent) 12%, var(--bg-selected))",
  },
  databaseTypeGreen: {
    color: "#22c55e",
    fontWeight: 600,
  },
  databaseTypeInteger: {
    color: "#3b82f6",
    fontWeight: 800,
  },
  databaseTypeString: {
    color: "#f59e0b",
    fontWeight: 800,
  },
  databaseTypeText: {
    color: "#14b8a6",
    fontWeight: 800,
  },
  databaseTypeNumber: {
    color: "#8b5cf6",
    fontWeight: 800,
  },
  databaseTypeDate: {
    color: "#ec4899",
    fontWeight: 800,
  },
  databaseTypeBoolean: {
    color: "#ef4444",
    fontWeight: 800,
  },
  databaseTypeJson: {
    color: "#06b6d4",
    fontWeight: 800,
  },
  databaseTypeBinary: {
    color: "#64748b",
    fontWeight: 800,
  },
  databaseTypeDefault: {
    color: "#94a3b8",
    fontWeight: 800,
  },
  databaseGridCellContent: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  databaseGridCellValue: {
    minWidth: 0,
    flex: "1 1 auto",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  databaseGridCellPreviewButton: {
    width: 18,
    height: 18,
    borderRadius: "50%",
    border: "1px solid var(--border-medium, #555)",
    background: "transparent",
    color: "var(--text-hint)",
    fontSize: 11,
    fontWeight: 700,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  databaseCellSelected: {
    outline: "2px solid var(--accent)",
    outlineOffset: -2,
  },
  databaseCellDetailPanel: {
    borderTop: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    padding: "12px 16px",
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
    fontSize: 13,
  },
  databaseCellDetailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
    gap: "6px 16px",
  },
  databaseCellDetailField: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  },
  databaseCellDetailLabel: {
    fontSize: 11,
    color: "var(--text-hint)",
    fontWeight: 600,
    textTransform: "uppercase" as const,
  },
  databaseCellDetailValue: {
    fontSize: 13,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    wordBreak: "break-all" as const,
  },
  databaseTabBar: {
    display: "flex",
    alignItems: "center",
    gap: 0,
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    overflow: "auto",
    flexShrink: 0,
  },
  databaseTab: {
    height: 34,
    padding: "0 14px",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    border: "none",
    borderBottom: "2px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  databaseTabActive: {
    borderBottomColor: "var(--accent)",
    color: "var(--text-primary)",
    fontWeight: 600,
  },
  databaseTabClose: {
    width: 16,
    height: 16,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    background: "transparent",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
    color: "var(--text-hint)",
    padding: 0,
    fontSize: 12,
    lineHeight: 1,
  },
  databaseGridFooter: {
    height: 38,
    flexShrink: 0,
    display: "grid",
    gridTemplateColumns: "minmax(120px, 1fr) minmax(0, 2fr) max-content",
    alignItems: "center",
    gap: 12,
    padding: "0 14px",
    borderTop: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  databaseGridFooterRows: {
    minWidth: 0,
    color: "var(--text-muted)",
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseGridFooterSql: {
    minWidth: 0,
    justifySelf: "center",
    maxWidth: "100%",
    color: "var(--text-hint)",
    fontFamily: "Monaco, Menlo, Consolas, var(--font-mono)",
    fontSize: 11.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseGridFooterPager: {
    justifySelf: "end",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minWidth: "max-content",
    whiteSpace: "nowrap" as const,
  },
  databaseGridTypeBadge: {
    maxWidth: 88,
    height: 16,
    flex: "0 0 auto",
    display: "inline-flex",
    alignItems: "center",
    border: "1px solid var(--border-dim)",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-hint)",
    padding: "0 5px",
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1,
    letterSpacing: 0,
    textTransform: "uppercase" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseTd: {
    height: 34,
    padding: "0 8px",
    borderBottom: "1px solid var(--border-medium)",
    borderRight: "1px solid var(--border-medium)",
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseGridControlTh: {
    textAlign: "center" as const,
    verticalAlign: "middle" as const,
    padding: "0 6px",
  },
  databaseGridControlTd: {
    textAlign: "center" as const,
    verticalAlign: "middle" as const,
    padding: "0 6px",
  },
  databaseGridRowNumberButton: {
    width: "100%",
    minWidth: 28,
    height: 24,
    border: "none",
    borderRadius: 0,
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontFamily: "Monaco, Menlo, Consolas, var(--font-mono)",
    fontSize: 12,
    fontWeight: 700,
  },
  databaseGridRowNumberButtonSelected: {
    background: "var(--bg-selected)",
    color: "var(--text-primary)",
  },
  databaseCellInput: {
    width: "100%",
    height: 28,
    border: "1px solid transparent",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12,
    padding: "0 5px",
    outline: "none",
  },
  databaseEmpty: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    fontSize: 13,
  },
  databaseError: {
    color: "var(--danger)",
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseButtonRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap" as const,
  },
  databaseBrowserRoot: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "300px minmax(0, 1fr)",
    overflow: "hidden",
  },
  databaseBrowserSidebar: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    borderRight: "1px solid var(--border-dim)",
    overflow: "hidden",
  },
  databaseBrowserMain: {
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    overflow: "hidden",
  },
  databaseSearchBox: {
    height: 32,
    display: "flex",
    alignItems: "center",
    gap: 7,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-input)",
    color: "var(--text-muted)",
    padding: "0 9px",
  },
  databaseSearchInput: {
    flex: 1,
    minWidth: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
  },
  databasePill: {
    height: 20,
    display: "inline-flex",
    alignItems: "center",
    border: "1px solid var(--border-dim)",
    borderRadius: 999,
    padding: "0 7px",
    color: "var(--text-hint)",
    fontSize: 10.5,
    textTransform: "uppercase" as const,
  },
  databaseLargeTextArea: {
    flex: 1,
    minHeight: 160,
    resize: "none" as const,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    padding: 10,
    outline: "none",
  },
  databaseEmptyCompact: {
    padding: 12,
    color: "var(--text-muted)",
    fontSize: 12,
  },
  databaseDocumentList: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  databaseDocumentCard: {
    margin: 0,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
    color: "var(--text-secondary)",
    padding: 10,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap" as const,
  },
  databaseDiagramCanvas: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    display: "flex",
    alignItems: "flex-start",
    alignContent: "flex-start",
    flexWrap: "wrap" as const,
    gap: 16,
    padding: 16,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
  },
  databaseDiagramNode: {
    width: 220,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-card)",
    overflow: "hidden",
  },
  databaseDiagramNodeTitle: {
    padding: "8px 10px",
    borderBottom: "1px solid var(--border-dim)",
    fontSize: 12.5,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  databaseDiagramColumn: {
    padding: "5px 10px",
    borderBottom: "1px solid var(--border-dim)",
    fontSize: 11.5,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },

  // DBX-style button primitives
  dbxButton: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "var(--accent)",
    color: "var(--accent-foreground)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  dbxButtonOutline: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  dbxButtonSecondary: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "var(--bg-subtle)",
    color: "var(--text-secondary)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  dbxButtonGhost: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  dbxButtonDestructive: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 10px",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "var(--danger-subtle)",
    color: "var(--danger)",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  dbxButtonSm: {
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "0 10px",
    border: "1px solid transparent",
    borderRadius: 10,
    background: "var(--accent)",
    color: "var(--accent-foreground)",
    fontSize: 12.8,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  dbxButtonXs: {
    height: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "0 8px",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "var(--accent)",
    color: "var(--accent-foreground)",
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s ease",
    whiteSpace: "nowrap",
  },
  dbxIconButton: {
    width: 32,
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  dbxIconButtonSm: {
    width: 28,
    height: 28,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid transparent",
    borderRadius: 10,
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  dbxIconButtonXs: {
    width: 24,
    height: 24,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid transparent",
    borderRadius: 8,
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
    transition: "all 0.15s ease",
  },
  dbxButtonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
    pointerEvents: "none" as const,
  },
} satisfies Record<string, React.CSSProperties>;
