import type React from "react";

export const database = {
  databaseRoot: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "284px minmax(0, 1fr)",
    gridTemplateRows: "40px minmax(0, 1fr)",
    background: "var(--bg-panel)",
    color: "var(--text-primary)",
  },
  databaseTopToolbar: {
    gridColumn: "1 / -1",
    height: 40,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 4,
    padding: "0 8px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
  },
  databaseToolbarButton: {
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 9px",
    border: "none",
    borderRadius: 7,
    background: "transparent",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
  },
  databaseSidebar: {
    width: 284,
    gridColumn: "1",
    gridRow: "2",
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    minHeight: 0,
  },
  databaseSidebarHeader: {
    padding: "12px 12px 10px",
    borderBottom: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  databaseTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  databaseTitle: {
    fontSize: 13,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  databaseActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 6,
  },
  databaseSmallButton: {
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
  },
  databaseIconButton: {
    width: 30,
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    borderRadius: 7,
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
  databaseDialogOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 3000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.28)",
  },
  databaseDialog: {
    width: 420,
    maxWidth: "calc(100vw - 32px)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-panel)",
    boxShadow: "0 18px 48px rgba(0, 0, 0, 0.22)",
    color: "var(--text-primary)",
  },
  databaseConnectionDialog: {
    width: 720,
    maxWidth: "calc(100vw - 32px)",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-panel)",
    boxShadow: "0 18px 48px rgba(0, 0, 0, 0.22)",
    color: "var(--text-primary)",
  },
  databaseDialogHeader: {
    padding: "14px 16px 10px",
    borderBottom: "1px solid var(--border-dim)",
    fontSize: 13,
    fontWeight: 750,
  },
  databaseDialogBody: {
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  databaseDialogIntro: {
    fontSize: 12.5,
    color: "var(--text-muted)",
  },
  databaseTypeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 10,
    maxHeight: "58vh",
    overflowY: "auto",
  },
  databaseTypeCard: {
    minHeight: 92,
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
  },
  databaseTypeCardSelected: {
    borderColor: "var(--border-focus)",
    background: "var(--accent-subtle)",
    color: "var(--text-primary)",
    boxShadow: "0 0 0 1px var(--border-focus)",
  },
  databaseTypeIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 12,
    fontWeight: 800,
  },
  databaseTypeIconSmall: {
    width: 24,
    height: 24,
    borderRadius: 6,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    fontWeight: 800,
  },
  databaseTypeLabel: {
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12.5,
    fontWeight: 650,
  },
  databaseConfigHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  databaseTypeMiniCard: {
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    padding: "0 9px",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 650,
  },
  databaseConfigTabs: {
    display: "flex",
    gap: 4,
    borderBottom: "1px solid var(--border-dim)",
    paddingBottom: 8,
  },
  databaseConfigTab: {
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "0 9px",
    border: "1px solid transparent",
    borderRadius: 7,
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 650,
  },
  databaseConfigTabActive: {
    borderColor: "var(--border-medium)",
    background: "var(--bg-selected)",
    color: "var(--text-primary)",
  },
  databaseDialogFormGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 12,
  },
  databaseInputButtonRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  databaseDialogPanel: {
    minHeight: 160,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
    padding: 14,
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
  },
  databaseSwitchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--text-secondary)",
  },
  databaseDialogHint: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-muted)",
  },
  databaseDialogField: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  databaseDialogLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    color: "var(--text-muted)",
  },
  databaseDialogInput: {
    height: 32,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    padding: "0 9px",
    outline: "none",
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
  },
  databaseDialogFooter: {
    padding: "10px 16px 14px",
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
  },
  databaseWorkspacePanel: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 16,
    overflow: "auto",
  },
  databaseWorkspaceHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  databaseWorkspaceTitle: {
    fontSize: 14,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  databaseSqlPreview: {
    flex: 1,
    minHeight: 220,
    margin: 0,
    padding: 12,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    overflow: "auto",
    whiteSpace: "pre-wrap" as const,
  },
  databaseSection: {
    padding: "10px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  databaseSectionTitle: {
    padding: "0 6px 3px",
    fontSize: 10.5,
    fontWeight: 750,
    color: "var(--text-hint)",
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
  },
  databaseScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  databaseListButton: {
    width: "100%",
    minHeight: 34,
    padding: "7px 8px",
    border: "1px solid transparent",
    borderRadius: 7,
    background: "transparent",
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    textAlign: "left" as const,
    cursor: "pointer",
    fontSize: 12.5,
  },
  databaseListButtonActive: {
    background: "var(--bg-selected)",
    borderColor: "var(--border-medium)",
    color: "var(--text-primary)",
  },
  databaseMain: {
    gridColumn: "2",
    gridRow: "2",
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  databaseTopbar: {
    minHeight: 50,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  databasePath: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12,
    color: "var(--text-muted)",
  },
  databaseSqlPanel: {
    flexShrink: 0,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border-dim)",
    display: "flex",
    gap: 8,
    alignItems: "stretch",
  },
  databaseSqlInput: {
    flex: 1,
    minHeight: 68,
    maxHeight: 120,
    resize: "vertical" as const,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    padding: "8px 10px",
    outline: "none",
  },
  databaseToolbar: {
    height: 42,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  databaseTableWrap: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    background: "var(--bg-panel)",
  },
  databaseTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    tableLayout: "fixed" as const,
    fontSize: 12,
  },
  databaseTh: {
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
    height: 32,
    padding: "0 8px",
    borderBottom: "1px solid var(--border-medium)",
    borderRight: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    color: "var(--text-secondary)",
    fontWeight: 700,
    textAlign: "left" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseTd: {
    height: 34,
    padding: "0 8px",
    borderBottom: "1px solid var(--border-dim)",
    borderRight: "1px solid var(--border-dim)",
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseCellInput: {
    width: "100%",
    height: 28,
    border: "1px solid transparent",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12,
    padding: "0 5px",
    outline: "none",
  },
  databaseEmpty: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    fontSize: 13,
  },
  databaseError: {
    color: "var(--danger)",
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseButtonRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap" as const,
  },
  databaseBrowserRoot: {
    flex: 1,
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "300px minmax(0, 1fr)",
    overflow: "hidden",
  },
  databaseBrowserSidebar: {
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    borderRight: "1px solid var(--border-dim)",
    overflow: "hidden",
  },
  databaseBrowserMain: {
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 12,
    overflow: "hidden",
  },
  databaseSearchBox: {
    height: 32,
    display: "flex",
    alignItems: "center",
    gap: 7,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-input)",
    color: "var(--text-muted)",
    padding: "0 9px",
  },
  databaseSearchInput: {
    flex: 1,
    minWidth: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 12.5,
  },
  databasePill: {
    height: 20,
    display: "inline-flex",
    alignItems: "center",
    border: "1px solid var(--border-dim)",
    borderRadius: 999,
    padding: "0 7px",
    color: "var(--text-hint)",
    fontSize: 10.5,
    textTransform: "uppercase" as const,
  },
  databaseLargeTextArea: {
    flex: 1,
    minHeight: 160,
    resize: "none" as const,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    padding: 10,
    outline: "none",
  },
  databaseEmptyCompact: {
    padding: 12,
    color: "var(--text-muted)",
    fontSize: 12,
  },
  databaseDocumentList: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  databaseDocumentCard: {
    margin: 0,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
    color: "var(--text-secondary)",
    padding: 10,
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap" as const,
  },
  databaseDiagramCanvas: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    display: "flex",
    alignItems: "flex-start",
    alignContent: "flex-start",
    flexWrap: "wrap" as const,
    gap: 16,
    padding: 16,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-subtle)",
  },
  databaseDiagramNode: {
    width: 220,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-card)",
    overflow: "hidden",
  },
  databaseDiagramNodeTitle: {
    padding: "8px 10px",
    borderBottom: "1px solid var(--border-dim)",
    fontSize: 12.5,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  databaseDiagramColumn: {
    padding: "5px 10px",
    borderBottom: "1px solid var(--border-dim)",
    fontSize: 11.5,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
