import type React from "react";

export const database = {
  databaseRoot: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    background: "var(--bg-panel)",
    color: "var(--text-primary)",
  },
  databaseSidebar: {
    width: 284,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    minHeight: 0,
  },
  databaseSidebarHeader: {
    padding: "12px 12px 10px",
    borderBottom: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  databaseTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  databaseTitle: {
    fontSize: 13,
    fontWeight: 750,
    color: "var(--text-primary)",
  },
  databaseActions: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 6,
  },
  databaseSmallButton: {
    height: 30,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    background: "var(--bg-card)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
  },
  databaseSection: {
    padding: "10px 8px",
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  databaseSectionTitle: {
    padding: "0 6px 3px",
    fontSize: 10.5,
    fontWeight: 750,
    color: "var(--text-hint)",
    textTransform: "uppercase" as const,
    letterSpacing: 0.6,
  },
  databaseScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
  },
  databaseListButton: {
    width: "100%",
    minHeight: 34,
    padding: "7px 8px",
    border: "1px solid transparent",
    borderRadius: 7,
    background: "transparent",
    color: "var(--text-secondary)",
    display: "flex",
    alignItems: "center",
    gap: 8,
    textAlign: "left" as const,
    cursor: "pointer",
    fontSize: 12.5,
  },
  databaseListButtonActive: {
    background: "var(--bg-selected)",
    borderColor: "var(--border-medium)",
    color: "var(--text-primary)",
  },
  databaseMain: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  databaseTopbar: {
    minHeight: 50,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  databasePath: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12,
    color: "var(--text-muted)",
  },
  databaseSqlPanel: {
    flexShrink: 0,
    padding: "10px 14px",
    borderBottom: "1px solid var(--border-dim)",
    display: "flex",
    gap: 8,
    alignItems: "stretch",
  },
  databaseSqlInput: {
    flex: 1,
    minHeight: 68,
    maxHeight: 120,
    resize: "vertical" as const,
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    padding: "8px 10px",
    outline: "none",
  },
  databaseToolbar: {
    height: 42,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 14px",
    borderBottom: "1px solid var(--border-dim)",
  },
  databaseTableWrap: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    background: "var(--bg-panel)",
  },
  databaseTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    tableLayout: "fixed" as const,
    fontSize: 12,
  },
  databaseTh: {
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
    height: 32,
    padding: "0 8px",
    borderBottom: "1px solid var(--border-medium)",
    borderRight: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
    color: "var(--text-secondary)",
    fontWeight: 700,
    textAlign: "left" as const,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseTd: {
    height: 34,
    padding: "0 8px",
    borderBottom: "1px solid var(--border-dim)",
    borderRight: "1px solid var(--border-dim)",
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  databaseCellInput: {
    width: "100%",
    height: 28,
    border: "1px solid transparent",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12,
    padding: "0 5px",
    outline: "none",
  },
  databaseEmpty: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-muted)",
    fontSize: 13,
  },
  databaseError: {
    color: "var(--danger)",
    fontSize: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
