import type React from "react";

import { ROW_HEIGHT } from "../components/file-explorer/types";

export const panels = {
  newTaskOuter: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 48px",
    position: "relative",
    overflow: "visible",
  },
  newTaskHeader: {
    marginBottom: 20,
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  newTaskClaudeGif: {
    display: "block",
    width: "min(128px, 32vw)",
    height: "auto",
    marginBottom: 10,
    objectFit: "contain",
  },
  newTaskTitle: {
    display: "block",
    fontSize: 22,
    fontWeight: 700,
    color: "var(--text-primary)",
    letterSpacing: -0.3,
    marginBottom: 8,
  },
  newTaskMeta: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-muted)",
  },
  metaChip: {
    background: "var(--accent-subtle)",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-sm)",
    padding: "2px 7px",
    fontSize: 12,
  },
  composeCard: {
    width: "100%",
    maxWidth: 820,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-lg) var(--radius-lg) 0 0",
    boxShadow: "var(--shadow-compose)",
    overflow: "visible",
  },
  agentMissingMdBanner: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    width: "100%",
    maxWidth: 700,
    marginBottom: 10,
    padding: "10px 14px",
    background: "var(--warning-surface)",
    border: "1px solid var(--warning-border)",
    borderRadius: "var(--radius-md)",
    boxSizing: "border-box" as const,
  },
  agentMissingMdBody: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
    minWidth: 0,
    flex: 1,
  },
  agentMissingMdInitBtn: {
    alignSelf: "flex-start",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    background: "transparent",
    color: "var(--warning)",
    border: "1px solid var(--warning-border)",
    borderRadius: 6,
    fontSize: 12.5,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 120ms ease",
  },
  hookFallbackIcon: {
    color: "var(--warning)",
    flexShrink: 0,
    marginTop: 1,
  },
  hookFallbackText: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  },
  // 项目栏状态指示：小圆点(默认)与待确认数量角标
  railStatusDot: {
    position: "absolute" as const,
    bottom: -1,
    right: -1,
    width: 9,
    height: 9,
    borderRadius: "50%",
    borderStyle: "solid" as const,
    borderWidth: 2,
    boxSizing: "border-box" as const,
    // 必须高于 railAvatarStacked(zIndex:1),否则被抬层的头像盖住
    zIndex: 2,
  },
  // 招手小人:绝对定位在头像右下,z-index 低于头像,缩回时被头像遮住
  railMascot: {
    position: "absolute" as const,
    left: 14,
    bottom: -3,
    height: 40,
    width: "auto" as const,
    zIndex: 0,
    pointerEvents: "none" as const,
  },
  // 头像抬到小人之上,使探头/缩回有被遮挡的层次
  railAvatarStacked: {
    position: "relative" as const,
    zIndex: 1,
  },
  railAttentionBadge: {
    position: "absolute" as const,
    top: -5,
    right: -5,
    minWidth: 16,
    height: 16,
    padding: "0 4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    background: "var(--color-warning)",
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1,
    borderStyle: "solid" as const,
    borderWidth: 2,
    boxSizing: "border-box" as const,
    pointerEvents: "none" as const,
    // 必须高于 railAvatarStacked(zIndex:1),否则被抬层的头像盖住
    zIndex: 2,
  },
  // 通用设置：开关(toggle switch)
  settingToggle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    width: "100%",
    padding: "12px 14px",
    borderRadius: "var(--radius-md)",
    border: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
    cursor: "pointer",
    textAlign: "left" as const,
  },
  settingToggleLabel: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  settingToggleTrack: {
    display: "inline-flex",
    alignItems: "center",
    flexShrink: 0,
    width: 40,
    height: 24,
    borderRadius: 999,
    padding: 3,
    boxSizing: "border-box" as const,
    transition: "background 0.12s",
  },
  settingToggleKnob: {
    display: "block",
    flexShrink: 0,
    width: 18,
    height: 18,
    borderRadius: 999,
    background: "var(--control-knob-bg)",
    transition: "transform 0.12s ease",
  },
  composeTextarea: {
    display: "block",
    width: "100%",
    padding: "22px 24px 12px",
    border: "none",
    outline: "none",
    resize: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 14,
    lineHeight: 1.65,
    fontFamily: "var(--font-ui)",
  },
  composeActionDock: {
    width: "100%",
    maxWidth: 820,
    marginTop: -1,
    padding: "6px 7px",
    borderRadius: "0 0 var(--radius-lg) var(--radius-lg)",
    border: "1px solid color-mix(in srgb, var(--border-medium) 76%, transparent)",
    borderTop: "none",
    background: "color-mix(in srgb, var(--bg-card) 74%, transparent)",
    backdropFilter: "blur(28px) saturate(1.32)",
    WebkitBackdropFilter: "blur(28px) saturate(1.32)",
    boxShadow: "var(--shadow-compose), inset 0 1px 0 rgba(255,255,255,0.06)",
  },
  composeActionRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
    width: "100%",
    flexWrap: "nowrap" as const,
  },
  toolbar: {
    flex: 1,
    minWidth: 0,
    borderTop: "none",
    minHeight: 30,
    padding: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "nowrap" as const,
    gap: 6,
    background: "transparent",
    borderRadius: "0 0 12px 12px",
    boxSizing: "border-box" as const,
  },
  toolbarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    minWidth: 0,
    flex: "0 1 auto",
    flexWrap: "nowrap" as const,
  },
  launchModeBar: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    flexShrink: 0,
    marginBottom: 0,
    padding: 0,
    boxSizing: "border-box" as const,
  },
  toolbarSpacer: {
    flex: "1 1 auto",
    minWidth: 0,
  },
  toolbarPlusBtn: {
    width: 24,
    height: 24,
    padding: 0,
    border: "none",
    borderRadius: 6,
    background: "transparent",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  toolbarIconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "5px 7px",
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
  },
  toolbarDivider: {
    width: 1,
    height: 18,
    background: "var(--border-dim)",
    margin: "0 2px",
    flexShrink: 0,
  },
  toolbarBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    minHeight: 26,
    padding: "3px 7px",
    background: "color-mix(in srgb, var(--bg-card) 42%, transparent)",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-muted)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    flex: "0 1 auto",
    transition: "background 0.15s, border-color 0.15s, opacity 0.15s",
  },
  toolbarBtnIconOnly: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 28,
    minWidth: 28,
    height: 26,
    padding: 0,
    background: "color-mix(in srgb, var(--bg-card) 42%, transparent)",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-sm)",
    color: "var(--text-muted)",
    cursor: "pointer",
    flex: "0 0 auto",
    transition: "background 0.15s, border-color 0.15s, opacity 0.15s",
  },
  toolbarBtnActive: {
    background: "var(--control-active-bg)",
    border: "1px solid var(--border-strong)",
    color: "var(--control-active-fg)",
  },
  toolbarMenuContent: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-md)",
    boxShadow: "var(--shadow-popover)",
    padding: 4,
    minWidth: 180,
    zIndex: 9999,
  },
  toolbarActionMenuContent: {
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-md)",
    boxShadow: "var(--shadow-popover)",
    padding: 6,
    minWidth: 230,
    zIndex: 9999,
  },
  toolbarMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: "var(--radius-sm)",
    fontSize: 13,
    color: "var(--text-primary)",
    cursor: "pointer",
    outline: "none",
    userSelect: "none" as const,
  },
  toolbarMenuSeparator: {
    height: 1,
    background: "var(--border-dim)",
    margin: "6px 6px",
  },
  toolbarMenuItemIcon: {
    width: 14,
    height: 14,
    flexShrink: 0,
  },
  toolbarSwitchTrack: {
    width: 36,
    height: 20,
    borderRadius: 999,
    padding: 2,
    background: "var(--border-medium)",
    display: "inline-flex",
    alignItems: "center",
    boxSizing: "border-box" as const,
    transition: "background 0.15s",
  },
  toolbarSwitchThumb: {
    width: 16,
    height: 16,
    borderRadius: 999,
    background: "var(--bg-card)",
    boxShadow: "var(--shadow-switch-thumb)",
    transition: "transform 0.15s",
  },
  sendSplit: {
    display: "inline-flex",
    minHeight: 28,
    flex: "0 0 auto",
  },
  saveTodoBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "6px 12px",
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    transition: "opacity 0.15s",
  },
  sendBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minWidth: 74,
    minHeight: 28,
    padding: "5px 12px",
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    border: "none",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "var(--shadow-control)",
    whiteSpace: "nowrap" as const,
    transition: "opacity 0.15s, background 0.15s",
  },
  sendBtnIconOnly: {
    width: 32,
    minWidth: 32,
    padding: "5px 6px",
    gap: 0,
  },
  sendShortcutIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    minWidth: 18,
    color: "currentColor",
    opacity: 0.95,
  },
  sendShortcutTextKey: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 16,
    height: 14,
    fontSize: 10,
    fontWeight: 700,
    lineHeight: 1,
    fontFamily: "var(--font-ui)",
  },
  kbd: {
    display: "none",
    fontSize: 11,
    opacity: 0,
    background: "transparent",
    borderRadius: 3,
    padding: 0,
    fontFamily: "var(--font-ui)",
  },
  dropdownPanel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    zIndex: 100,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-md)",
    boxShadow: "var(--shadow-popover)",
    padding: 4,
    minWidth: 220,
  },
  dropdownOption: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 10px",
    borderRadius: 6,
    cursor: "pointer",
  },
  fileChipsRow: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: 6,
    padding: "10px 14px 4px",
    borderBottom: "1px solid var(--border-dim)",
  },
  fileChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "3px 8px 3px 7px",
    background: "var(--accent-subtle)",
    border: "1px solid color-mix(in srgb, var(--accent) 30%, transparent)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--accent)",
    maxWidth: 240,
  },
  fileChipName: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" as const },
  fileChipRemove: {
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    display: "flex",
    alignItems: "center",
    color: "var(--accent)",
    opacity: 0.6,
    marginLeft: 1,
    flexShrink: 0,
  },
  mentionDropdown: {
    position: "absolute" as const,
    bottom: "calc(100% + 6px)",
    left: 0,
    right: 0,
    zIndex: 200,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-md)",
    boxShadow: "var(--shadow-popover)",
    padding: 4,
    maxHeight: 260,
    overflowY: "auto" as const,
  },
  mentionOption: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionOptionName: { fontSize: 13, fontWeight: 500, color: "var(--text-primary)", flexShrink: 0 },
  mentionOptionDir: {
    fontSize: 11.5,
    color: "var(--text-hint)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    minWidth: 0,
  },
  mentionSeparator: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 3px",
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-hint)",
    letterSpacing: 0.4,
    textTransform: "uppercase" as const,
    userSelect: "none" as const,
  },
  mentionProjectItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 6,
    cursor: "pointer",
    minWidth: 0,
  },
  mentionCrossHeader: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px 5px",
    fontSize: 11.5,
    fontWeight: 500,
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border-dim)",
    marginBottom: 3,
    userSelect: "none" as const,
  },
  fileExplorerRoot: {
    flexShrink: 0,
    background: "var(--bg-sidebar)",
    borderLeft: "1px solid var(--border-dim)",
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  fileExplorerHeader: {
    height: 40,
    position: "relative" as const,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "0 12px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  fileExplorerHeaderTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    textTransform: "uppercase" as const,
    flex: 1,
    minWidth: 0,
  },
  fileExplorerSortControls: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  fileExplorerSortBtn: {
    height: 22,
    border: "1px solid var(--border-dim)",
    borderRadius: 4,
    background: "var(--bg-panel)",
    color: "var(--text-secondary)",
    cursor: "pointer",
    padding: "0 5px",
    fontSize: 10.5,
    fontFamily: "var(--font-ui)",
    lineHeight: 1,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    whiteSpace: "nowrap" as const,
  },
  fileExplorerSortBtnActive: {
    borderColor: "var(--accent)",
    color: "var(--control-active-fg)",
    background: "var(--control-active-bg)",
  },
  fileExplorerRefreshBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "var(--text-hint)",
    padding: 4,
    borderRadius: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  fileExplorerSearchOverlay: {
    position: "absolute" as const,
    zIndex: 2,
    left: 8,
    right: 42,
    top: 7,
    height: 26,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "0 7px",
    border: "1px solid var(--border-focus)",
    borderRadius: 6,
    background: "var(--bg-input)",
    color: "var(--text-muted)",
    boxShadow: "0 0 0 3px var(--accent-subtle)",
  },
  fileExplorerSearchInput: {
    flex: 1,
    minWidth: 0,
    height: "100%",
    border: 0,
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    font: "inherit",
    fontSize: 12,
  },
  fileExplorerSearchCloseBtn: {
    width: 20,
    height: 20,
    border: 0,
    borderRadius: 4,
    background: "transparent",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
  },
  fileExplorerRootLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 8px 3px 20px",
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  fileExplorerRootIcon: {
    width: 5,
    height: 14,
    borderRadius: 2,
    background: "var(--icon-folder-root)",
    flexShrink: 0,
    display: "inline-block",
  },
  fileSearchDialogBackdrop: {
    position: "fixed" as const,
    inset: 0,
    zIndex: 1600,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    paddingTop: "18vh",
    background: "color-mix(in srgb, var(--bg-root) 38%, transparent)",
  },
  fileSearchDialog: {
    width: "min(620px, calc(100vw - 56px))",
    maxHeight: "min(560px, calc(100vh - 180px))",
    display: "flex",
    flexDirection: "column" as const,
    padding: 10,
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-lg)",
    boxShadow: "var(--shadow-popover)",
    overflow: "hidden",
  },
  fileSearchDialogHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "2px 2px 8px",
    flexShrink: 0,
  },
  fileSearchDialogTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-hint)",
    letterSpacing: 0.7,
    textTransform: "uppercase" as const,
  },
  fileSearchBox: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    minHeight: 30,
    padding: "0 5px 0 9px",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-sm)",
    background: "var(--bg-card)",
    boxSizing: "border-box" as const,
  },
  fileSearchIcon: {
    flexShrink: 0,
    color: "var(--text-hint)",
  },
  fileSearchInput: {
    flex: 1,
    minWidth: 0,
    height: 26,
    padding: 0,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    fontSize: 12.5,
  },
  fileSearchClearBtn: {
    width: 20,
    height: 20,
    padding: 0,
    border: "none",
    borderRadius: 4,
    background: "transparent",
    color: "var(--text-hint)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  fileSearchTypeTrigger: {
    height: 22,
    maxWidth: 76,
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    padding: "0 5px 0 7px",
    border: "1px solid transparent",
    borderRadius: 5,
    background: "var(--accent-subtle)",
    color: "var(--text-muted)",
    fontFamily: "var(--font-ui)",
    fontSize: 11.5,
    fontWeight: 600,
    cursor: "pointer",
    outline: "none",
    flexShrink: 0,
    overflow: "hidden",
    whiteSpace: "nowrap" as const,
  },
  fileSearchTypeContent: {
    zIndex: 2000,
    background: "var(--bg-sidebar)",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-md)",
    boxShadow: "var(--shadow-popover)",
    padding: 4,
    minWidth: 132,
    overflow: "hidden",
  },
  fileSearchTypeItem: {
    height: 26,
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 28px 0 9px",
    borderRadius: 5,
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 12.5,
    outline: "none",
    position: "relative",
  },
  fileSearchTypeItemSelected: {
    background: "var(--control-active-bg)",
    color: "var(--control-active-fg)",
  },
  fileSearchResults: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto" as const,
    paddingTop: 7,
  },
  fileSearchEmpty: {
    padding: "16px 8px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },
  fileSearchResult: {
    width: "100%",
    minHeight: 34,
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "5px 7px",
    margin: "1px 0",
    border: "none",
    borderRadius: 5,
    background: "transparent",
    color: "var(--text-primary)",
    textAlign: "left" as const,
    cursor: "pointer",
    fontFamily: "var(--font-ui)",
    boxSizing: "border-box" as const,
  },
  fileSearchResultActive: {
    background: "var(--control-active-bg)",
    color: "var(--control-active-fg)",
  },
  fileSearchResultMain: {
    display: "flex",
    flexDirection: "column" as const,
    minWidth: 0,
    flex: 1,
    gap: 1,
  },
  fileSearchResultName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
  },
  fileSearchResultDir: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 11,
    color: "var(--text-hint)",
  },
  fileExplorerTreeScroll: {
    flex: 1,
    overflowY: "auto" as const,
    position: "relative" as const,
  },
  fileExplorerEmpty: {
    padding: "16px 12px",
    fontSize: 12,
    color: "var(--text-hint)",
    textAlign: "center" as const,
  },
  fileExplorerVirtualRow: {
    position: "absolute" as const,
    width: "100%",
  },
  fileIconFolder: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 18,
    height: 16,
    marginRight: 4,
    flexShrink: 0,
  },
  fileIconFile: {
    width: 18,
    height: 16,
    borderRadius: 2,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 4,
  },
  fileTreeRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    height: ROW_HEIGHT,
    paddingRight: 8,
    cursor: "pointer",
    borderRadius: 4,
    margin: "0 4px",
    boxSizing: "border-box" as const,
    userSelect: "none" as const,
  },
  fileTreeChevron: {
    width: 12,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    color: "var(--text-hint)",
  },
  fileTreeChevronSpacer: {
    width: 12,
    flexShrink: 0,
  },
  fileTreeRowLabel: {
    fontSize: 12.5,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    flex: 1,
    fontFamily: "var(--font-ui)",
  },
  fileTreeCreateRow: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    height: ROW_HEIGHT,
    paddingRight: 8,
    margin: "0 4px",
    boxSizing: "border-box" as const,
    background: "var(--bg-selected)",
    borderRadius: 4,
  },
  fileTreeCreateInput: {
    flex: 1,
    minWidth: 0,
    height: 18,
    padding: "0 4px",
    fontSize: 12.5,
    fontFamily: "var(--font-ui)",
    color: "var(--text-primary)",
    background: "var(--bg-input, var(--bg-sidebar))",
    border: "1px solid var(--accent)",
    borderRadius: 3,
    outline: "none",
  },
  fileCtxBackdrop: {
    position: "fixed" as const,
    inset: 0,
    zIndex: 999,
  },
  fileCtxMenu: {
    position: "fixed" as const,
    zIndex: 1000,
    background: "var(--bg-sidebar)",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    boxShadow: "var(--shadow-popover)",
    minWidth: 148,
    padding: "3px 0",
    fontSize: 12.5,
    color: "var(--text-primary)",
  },
  fileCtxSeparator: {
    height: 1,
    background: "var(--border-dim)",
    margin: "4px 6px",
  },
  fileCtxMenuItem: {
    display: "flex",
    alignItems: "center",
    width: "calc(100% - 8px)",
    height: 28,
    padding: "0 10px",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
    borderRadius: 6,
    margin: "2px 4px",
    transition: "background 0.15s ease",
    background: "transparent",
    border: "none",
    textAlign: "left" as const,
    fontSize: 13,
    fontWeight: 500,
    fontFamily: "var(--font-ui)",
    lineHeight: "28px",
    gap: 8,
    color: "var(--text-primary)",
  },
  attachmentsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    padding: "6px 12px 0",
  },
  imageAttachmentItem: {
    position: "relative",
    flexShrink: 0,
  },
  imageAttachmentImg: {
    width: 64,
    height: 64,
    objectFit: "cover",
    borderRadius: 6,
    display: "block",
    border: "1px solid var(--border)",
  },
  imageAttachmentRemove: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 16,
    height: 16,
    borderRadius: "50%",
    background: "var(--text-muted)",
    border: "none",
    color: "var(--bg)",
    fontSize: 10,
    lineHeight: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },
  textAttachmentChip: {
    position: "relative",
    width: 64,
    height: 64,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-secondary)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    flexShrink: 0,
  },
  textAttachmentIcon: {
    color: "var(--text-muted)",
  },
  textAttachmentSize: {
    fontSize: 10,
    color: "var(--text-hint)",
    fontWeight: 500,
  },
  textAttachmentRemove: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 16,
    height: 16,
    borderRadius: "50%",
    background: "var(--text-muted)",
    border: "none",
    color: "var(--bg)",
    fontSize: 10,
    lineHeight: "16px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
  },

  // ── HooksPanel (app settings → Hook 集成) ──────────────────────────────────
  hooksPanelBody: {
    flex: 1,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 14,
    padding: "20px",
  },
  hooksPanelLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 5,
    display: "block",
  },
  hooksPanelHint: { fontSize: 11, color: "var(--text-hint)", marginTop: 3, lineHeight: 1.5 },
  hooksPanelCard: {
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    padding: "10px 14px",
    background: "var(--bg-card)",
  },
  hooksPanelRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "6px 0",
    fontSize: 12,
    color: "var(--text-primary)",
    lineHeight: 1.5,
  },
  hooksPanelSubRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "0 0 6px",
    fontSize: 12,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  },
  hooksPanelRowSpacer: { width: 14, flexShrink: 0, display: "inline-block" },
  hooksPanelVersionLow: { color: "var(--warning)" },
  hooksPanelErrorRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "6px 0",
    fontSize: 12,
    color: "var(--danger)",
    lineHeight: 1.5,
  },
  hooksPanelActions: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap" as const,
    paddingTop: 4,
    borderTop: "1px solid var(--border-dim)",
    marginTop: 2,
  },
  hooksPanelPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 11px",
    background: "var(--primary-action-bg)",
    border: "1px solid transparent",
    borderRadius: 7,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--primary-action-fg)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  hooksPanelSecondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 11px",
    background: "var(--bg-card)",
    border: "1px solid var(--border-medium)",
    borderRadius: 7,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--text-primary)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  hooksPanelDangerBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    padding: "5px 11px",
    background: "var(--danger-surface)",
    border: "1px solid var(--danger-border)",
    borderRadius: 7,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--danger)",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  hooksPanelBtnDisabled: { opacity: 0.5, cursor: "not-allowed" as const },
  sshListWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
  },
  sshListHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  sshPanelTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  sshPanelSubtitle: {
    marginTop: 2,
    fontSize: 11,
    color: "var(--text-muted)",
  },
  sshIconButton: {
    width: 26,
    height: 26,
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  sshEmptyState: {
    minHeight: 150,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    border: "1px dashed var(--border-medium)",
    borderRadius: 8,
    color: "var(--text-muted)",
    background: "var(--bg-subtle)",
  },
  sshEmptyTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  sshConnectionRows: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    minHeight: 0,
    overflowY: "auto",
  },
  sshConnectionGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  sshConnectionGroupTitle: {
    padding: "0 2px",
    fontSize: 11,
    fontWeight: 750,
    color: "var(--text-muted)",
  },
  sshConnectionRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 9,
    minHeight: 46,
    padding: "7px 8px",
    border: "1px solid var(--border-dim)",
    borderRadius: 7,
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    textAlign: "left",
    cursor: "pointer",
  },
  sshConnectionRowSelected: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 9,
    minHeight: 46,
    padding: "7px 8px",
    border: "1px solid var(--control-active-fg)",
    borderRadius: 7,
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    textAlign: "left",
    cursor: "pointer",
  },
  sshConnectionText: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  sshConnectionName: {
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sshConnectionMeta: {
    fontSize: 11,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sshConnectionActions: {
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
  },
  sshRowAction: {
    width: 22,
    height: 22,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
    color: "var(--text-muted)",
  },
  sshDialogOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 3000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(0, 0, 0, 0.34)",
  },
  sshDialog: {
    width: "min(460px, calc(100vw - 36px))",
    maxHeight: "calc(100vh - 36px)",
    display: "flex",
    flexDirection: "column",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-lg)",
    background: "var(--bg-card)",
    boxShadow: "var(--shadow-popover)",
    overflow: "hidden",
  },
  sshProjectDialog: {
    width: "min(920px, calc(100vw - 36px))",
  },
  sshProjectPage: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-panel)",
  },
  sshProjectPageHeader: {
    minHeight: 64,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "14px 22px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
  },
  sshProjectPageTitle: {
    fontSize: 15,
    fontWeight: 740,
    color: "var(--text-primary)",
  },
  sshProjectPageSubtitle: {
    marginTop: 3,
    fontSize: 12,
    color: "var(--text-muted)",
  },
  sshProjectPageBody: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    padding: "18px 22px 22px",
  },
  sshProjectPageFooter: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 22px",
    borderTop: "1px solid var(--border-dim)",
    background: "var(--bg-sidebar)",
  },
  sshDialogHeader: {
    height: 44,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 12px 0 16px",
    borderBottom: "1px solid var(--border-dim)",
  },
  sshDialogTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
  },
  sshDialogBody: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: 16,
    overflowY: "auto",
  },
  sshProjectConnectionPicker: {
    display: "flex",
    flexDirection: "column",
    gap: 18,
  },
  sshProjectGroupSection: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  sshProjectGroupTitle: {
    fontSize: 12,
    fontWeight: 750,
    color: "var(--text-secondary)",
  },
  sshProjectCardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))",
    gap: 10,
  },
  sshProjectCard: {
    minWidth: 0,
    minHeight: 58,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-md)",
    background: "color-mix(in srgb, var(--bg-card) 78%, var(--bg-hover))",
    color: "var(--text-primary)",
    cursor: "pointer",
    textAlign: "left" as const,
    position: "relative" as const,
  },
  sshProjectCardSelected: {
    minWidth: 0,
    minHeight: 58,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    border: "1px solid var(--border-focus)",
    borderRadius: "var(--radius-md)",
    background: "var(--control-active-bg)",
    color: "var(--control-active-fg)",
    cursor: "pointer",
    textAlign: "left" as const,
    boxShadow: "0 0 0 3px var(--accent-subtle)",
    position: "relative" as const,
  },
  sshProjectCardIcon: {
    width: 34,
    height: 34,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "var(--radius-sm)",
    background: "var(--accent-subtle)",
    color: "var(--accent)",
  },
  sshProjectCardSelect: {
    minWidth: 0,
    flex: "1 1 auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: 0,
    border: "none",
    background: "transparent",
    color: "inherit",
    cursor: "pointer",
    textAlign: "left" as const,
  },
  sshProjectCardText: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  sshProjectCardName: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 13.5,
    fontWeight: 700,
  },
  sshProjectCardMeta: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
    fontSize: 11.5,
    color: "var(--text-muted)",
  },
  sshProjectCardEdit: {
    width: 28,
    height: 28,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    color: "var(--text-muted)",
    background: "color-mix(in srgb, var(--bg-card) 62%, transparent)",
    border: "1px solid var(--border-dim)",
    cursor: "pointer",
  },
  sshField: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  sshLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
  },
  sshInput: {
    width: "100%",
    height: 32,
    boxSizing: "border-box",
    padding: "0 9px",
    border: "1px solid var(--border-medium)",
    borderRadius: 6,
    outline: "none",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
  },
  sshInputInvalid: {
    width: "100%",
    height: 32,
    boxSizing: "border-box",
    padding: "0 9px",
    border: "1px solid var(--danger)",
    borderRadius: 6,
    outline: "none",
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    fontSize: 13,
    fontFamily: "var(--font-ui)",
  },
  sshErrorText: {
    fontSize: 11,
    color: "var(--danger)",
  },
  sshSecretNote: {
    padding: 0,
    border: "none",
    borderStyle: "none",
    borderRadius: 0,
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 11.5,
    lineHeight: 1.45,
  },
  sshDialogFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    padding: "12px 16px",
    borderTop: "1px solid var(--border-dim)",
  },
  sshPrimaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 28,
    padding: "0 12px",
    border: "1px solid transparent",
    borderRadius: 6,
    background: "var(--primary-action-bg)",
    color: "var(--primary-action-fg)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "pointer",
  },
  sshPrimaryButtonDisabled: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 28,
    padding: "0 12px",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    background: "var(--bg-hover)",
    color: "var(--text-hint)",
    fontSize: 12,
    fontWeight: 650,
    cursor: "not-allowed",
  },
  sshSecondaryButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 28,
    padding: "0 12px",
    border: "1px solid var(--border-medium)",
    borderRadius: 6,
    background: "var(--bg-card)",
    color: "var(--text-primary)",
    fontSize: 12,
    fontWeight: 550,
    cursor: "pointer",
  },
  sshPanel: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: 12,
    boxSizing: "border-box",
    borderLeft: "1px solid var(--border-dim)",
    background: "var(--bg-panel)",
    minWidth: 0,
  },
  sshCenterPanel: {
    borderLeft: "none",
    padding: 14,
  },
  sshTerminalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 2,
  },
  sshTerminalTitle: {
    minWidth: 0,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  sshErrorBanner: {
    padding: "7px 9px",
    border: "1px solid var(--danger-border)",
    borderRadius: 7,
    background: "var(--danger-surface)",
    color: "var(--danger)",
    fontSize: 11.5,
    lineHeight: 1.45,
  },
  sshTerminalFrame: {
    flex: 1,
    minHeight: 180,
    position: "relative",
    overflow: "hidden",
    border: "1px solid var(--border-dim)",
    borderRadius: 7,
    background: "var(--bg-panel)",
  },
  sshTerminalCanvas: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    padding: "4px 6px",
    cursor: "text",
  },
  sshTerminalPlaceholder: {
    height: "100%",
    minHeight: 180,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    boxSizing: "border-box",
    textAlign: "center",
    color: "var(--text-muted)",
    fontSize: 12,
    lineHeight: 1.5,
  },
} satisfies Record<string, React.CSSProperties>;
