import type React from "react";

/**
 * Remote access settings intentionally use the shared semantic theme tokens.
 * The layout is fluid because the settings dialog can become quite short or
 * narrow on smaller desktop windows.
 */
export const remoteAccess = {
  remotePanel: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollbarGutter: "stable",
    padding: 20,
    boxSizing: "border-box",
    color: "var(--text-primary)",
  },
  /** 超宽窗口下内容居中限宽,避免卡片被拉伸得过长。 */
  remotePanelInner: {
    width: "100%",
    maxWidth: 980,
    margin: "0 auto",
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  remoteIntro: {
    maxWidth: 760,
    margin: 0,
    color: "var(--text-muted)",
    fontSize: 12.5,
    lineHeight: 1.65,
  },
  remoteStatusCard: {
    minWidth: 0,
    display: "flex",
    alignItems: "stretch",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 18,
    padding: "17px 18px",
    border: "1px solid color-mix(in srgb, var(--accent) 18%, var(--border-medium))",
    borderRadius: "var(--radius-lg)",
    background: "color-mix(in srgb, var(--bg-card) 82%, transparent)",
    backdropFilter: "blur(14px) saturate(1.12)",
    WebkitBackdropFilter: "blur(14px) saturate(1.12)",
    boxShadow:
      "inset 0 1px 0 color-mix(in srgb, white 7%, transparent), 0 8px 22px color-mix(in srgb, var(--text-primary) 5%, transparent)",
  },
  remoteStatusHeader: {
    minWidth: 0,
    flex: "1 1 340px",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 14,
  },
  remoteStatusIdentity: {
    minWidth: 0,
    flex: "1 1 240px",
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
  },
  remoteStatusIcon: {
    width: 38,
    height: 38,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "var(--radius-md)",
    background: "var(--accent-subtle)",
    color: "var(--accent)",
    boxShadow: "inset 0 0 0 1px color-mix(in srgb, var(--accent) 16%, transparent)",
  },
  remoteStatusLabel: {
    marginBottom: 3,
    color: "var(--text-muted)",
    fontSize: 10.5,
    fontWeight: 700,
    lineHeight: 1.3,
    letterSpacing: 0.45,
    textTransform: "uppercase",
  },
  remoteStatusTitle: {
    margin: 0,
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 720,
    lineHeight: 1.35,
  },
  remoteStatusCopyRow: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 7,
    marginTop: 6,
  },
  remoteStatusEndpoint: {
    minWidth: 0,
    overflow: "hidden",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    lineHeight: 1.45,
    overflowWrap: "anywhere",
  },
  remoteCopyButton: {
    minWidth: 26,
    minHeight: 26,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    padding: "4px 7px",
    border: "1px solid var(--border-dim)",
    borderRadius: 7,
    background: "color-mix(in srgb, var(--bg-card) 68%, transparent)",
    color: "var(--text-muted)",
    fontFamily: "var(--font-ui)",
    fontSize: 10.5,
    cursor: "pointer",
  },
  remoteStatusMeta: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 9,
    color: "var(--text-muted)",
    fontSize: 11.5,
    lineHeight: 1.4,
  },
  remoteStatusActions: {
    flex: "1 1 320px",
    minWidth: 260,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 12,
  },
  remoteAddressField: {
    minWidth: 180,
    flex: "1 1 190px",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 5,
  },
  remoteAddressSelect: {
    width: "100%",
    minWidth: 180,
    minHeight: 32,
    boxSizing: "border-box",
    padding: "6px 28px 6px 9px",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-sm)",
    outline: "none",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 11.5,
    boxShadow: "var(--shadow-control)",
  },
  remotePortField: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 5,
  },
  remotePortInput: {
    width: 96,
    minHeight: 32,
    boxSizing: "border-box",
    padding: "6px 9px",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-sm)",
    outline: "none",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12.5,
    boxShadow: "var(--shadow-control)",
  },
  remoteSectionGrid: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 286px), 1fr))",
    alignItems: "stretch",
    gap: 14,
  },
  remoteSection: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: "16px 17px",
    border: "1px solid color-mix(in srgb, var(--border-medium) 88%, transparent)",
    borderRadius: "var(--radius-lg)",
    background: "color-mix(in srgb, var(--bg-card) 70%, transparent)",
    backdropFilter: "blur(12px) saturate(1.08)",
    WebkitBackdropFilter: "blur(12px) saturate(1.08)",
    boxShadow: "inset 0 1px 0 color-mix(in srgb, white 6%, transparent)",
  },
  remoteSectionHeader: {
    minWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  remoteSectionTitle: {
    margin: 0,
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
    lineHeight: 1.4,
  },
  remoteSectionHint: {
    margin: "3px 0 0",
    color: "var(--text-hint)",
    fontSize: 11,
    lineHeight: 1.5,
  },
  remotePairingBody: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 10,
  },
  remotePairingEmpty: {
    width: "100%",
    minHeight: 172,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: "20px 16px",
    border: "1px dashed var(--border-medium)",
    borderRadius: "var(--radius-md)",
    background: "color-mix(in srgb, var(--bg-subtle) 58%, transparent)",
    color: "var(--text-muted)",
    textAlign: "center",
    fontSize: 11.5,
    lineHeight: 1.55,
  },
  remoteQrShell: {
    width: "fit-content",
    maxWidth: "100%",
    alignSelf: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 9,
    boxSizing: "border-box",
    padding: 14,
    overflow: "hidden",
    border: "1px solid color-mix(in srgb, var(--border-medium) 70%, #d4d4d8)",
    borderRadius: "var(--radius-md)",
    background: "#ffffff",
    boxShadow: "0 8px 22px rgba(24, 24, 27, 0.1)",
  },
  remoteQrMeta: {
    maxWidth: 214,
    color: "#52525b",
    fontFamily: "var(--font-mono)",
    fontSize: 10.5,
    lineHeight: 1.45,
    textAlign: "center",
    overflowWrap: "anywhere",
  },
  remoteActionRow: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 9,
  },
  remotePairingNotice: {
    width: "100%",
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    gap: 7,
    padding: "8px 10px",
    border: "1px solid color-mix(in srgb, var(--success) 26%, var(--border-dim))",
    borderRadius: "var(--radius-sm)",
    background: "color-mix(in srgb, var(--success) 8%, transparent)",
    color: "var(--success)",
    fontSize: 11.5,
    lineHeight: 1.45,
  },
  remoteDeviceList: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 7,
  },
  remoteDeviceRow: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 10px",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-md)",
    background: "color-mix(in srgb, var(--bg-subtle) 60%, transparent)",
  },
  remoteDeviceIcon: {
    width: 30,
    height: 30,
    flexShrink: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "var(--radius-sm)",
    background: "var(--accent-subtle)",
    color: "var(--accent)",
  },
  remoteDeviceInfo: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  remoteDeviceNameRow: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 7,
  },
  remoteDeviceName: {
    minWidth: 0,
    overflow: "hidden",
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontWeight: 650,
    lineHeight: 1.35,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  remoteDeviceMeta: {
    minWidth: 0,
    overflow: "hidden",
    color: "var(--text-hint)",
    fontSize: 10.5,
    lineHeight: 1.4,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  remoteDeviceState: {
    flexShrink: 0,
    color: "var(--text-muted)",
    fontSize: 10.5,
    fontWeight: 600,
    lineHeight: 1.3,
  },
  remoteStatusDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
    display: "inline-block",
    borderRadius: "50%",
    background: "var(--success)",
    boxShadow: "0 0 0 3px color-mix(in srgb, var(--success) 12%, transparent)",
  },
  remoteDisclosure: {
    minWidth: 0,
    overflow: "hidden",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-lg)",
    background: "color-mix(in srgb, var(--bg-card) 62%, transparent)",
    backdropFilter: "blur(12px) saturate(1.08)",
    WebkitBackdropFilter: "blur(12px) saturate(1.08)",
  },
  remoteDisclosureHeader: {
    width: "100%",
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    padding: "13px 16px",
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "var(--font-ui)",
    cursor: "pointer",
    textAlign: "left",
  },
  remoteDisclosureTitleRow: {
    minWidth: 0,
    flex: 1,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  remoteDisclosureChevron: {
    flexShrink: 0,
    color: "var(--text-muted)",
    transition: "transform 160ms ease",
  },
  remoteDisclosureContent: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: "16px",
    borderTop: "1px solid var(--border-dim)",
  },
  remoteFormGrid: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 240px), 1fr))",
    gap: "13px 14px",
  },
  remoteField: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 5,
  },
  remoteFormFullWidth: {
    minWidth: 0,
    gridColumn: "1 / -1",
  },
  remoteLabel: {
    display: "block",
    color: "var(--text-secondary)",
    fontSize: 11.5,
    fontWeight: 650,
    lineHeight: 1.35,
  },
  remoteInput: {
    width: "100%",
    minWidth: 0,
    minHeight: 34,
    boxSizing: "border-box",
    padding: "7px 9px",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-sm)",
    outline: "none",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    boxShadow: "var(--shadow-control)",
  },
  remoteTextarea: {
    width: "100%",
    minWidth: 0,
    minHeight: 72,
    boxSizing: "border-box",
    padding: "8px 9px",
    resize: "vertical",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-sm)",
    outline: "none",
    background: "var(--bg-input)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12,
    lineHeight: 1.5,
    boxShadow: "var(--shadow-control)",
  },
  remoteFeedback: {
    minWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    color: "var(--text-muted)",
    fontSize: 11.5,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
  },
  remoteFeedbackSuccess: {
    minWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    color: "var(--success)",
    fontSize: 11.5,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
  },
  remoteError: {
    minWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    padding: "8px 10px",
    border: "1px solid var(--danger-border)",
    borderRadius: "var(--radius-sm)",
    background: "var(--danger-surface)",
    color: "var(--danger)",
    fontSize: 11.5,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
  },
  remoteWarning: {
    minWidth: 0,
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    padding: "8px 10px",
    border: "1px solid var(--warning-border)",
    borderRadius: "var(--radius-sm)",
    background: "var(--warning-surface)",
    color: "var(--warning)",
    fontSize: 11.5,
    lineHeight: 1.5,
    overflowWrap: "anywhere",
  },
  remoteEmptyState: {
    minWidth: 0,
    padding: "18px 12px",
    border: "1px dashed var(--border-medium)",
    borderRadius: "var(--radius-md)",
    background: "color-mix(in srgb, var(--bg-subtle) 54%, transparent)",
    color: "var(--text-hint)",
    fontSize: 11.5,
    lineHeight: 1.55,
    textAlign: "center",
  },
  remoteBadge: {
    maxWidth: "100%",
    minHeight: 22,
    boxSizing: "border-box",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 8px",
    border: "1px solid var(--border-dim)",
    borderRadius: 999,
    background: "color-mix(in srgb, var(--bg-subtle) 78%, transparent)",
    color: "var(--text-muted)",
    fontSize: 10.5,
    fontWeight: 650,
    lineHeight: 1.3,
    whiteSpace: "nowrap",
  },
  remoteBadgeSuccess: {
    borderColor: "color-mix(in srgb, var(--success) 28%, var(--border-dim))",
    background: "color-mix(in srgb, var(--success) 9%, transparent)",
    color: "var(--success)",
  },
  remoteBadgeWarning: {
    borderColor: "color-mix(in srgb, var(--warning) 28%, var(--border-dim))",
    background: "color-mix(in srgb, var(--warning) 9%, transparent)",
    color: "var(--warning)",
  },
  remoteBadgeDanger: {
    borderColor: "color-mix(in srgb, var(--danger) 28%, var(--border-dim))",
    background: "color-mix(in srgb, var(--danger) 8%, transparent)",
    color: "var(--danger)",
  },
  remoteBadgeMuted: {
    borderColor: "var(--border-dim)",
    background: "color-mix(in srgb, var(--bg-subtle) 72%, transparent)",
    color: "var(--text-hint)",
  },
} satisfies Record<string, React.CSSProperties>;
