import type React from "react";

const exportBtnBase = {
  display: "flex",
  alignItems: "center",
  gap: 5,
  padding: "4px 10px",
  background: "none",
  border: "1px solid var(--control-active-fg)",
  borderRadius: "var(--radius-sm)",
  fontSize: 12,
  color: "var(--control-active-fg)",
  flexShrink: 0,
} as const;

export const terminal = {
  runHeader: {
    padding: "16px 20px 8px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  runMetaBranchRow: {
    marginTop: 4,
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  cancelBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  },
  exportBtn: { ...exportBtnBase, cursor: "pointer" as const },
  exportBtnBusy: { ...exportBtnBase, cursor: "not-allowed" as const, opacity: 0.6 },
  resumeBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "var(--control-active-bg)",
    border: "1px solid var(--border-strong)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    color: "var(--control-active-fg)",
    cursor: "pointer",
    flexShrink: 0,
  },
  doneBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid rgba(46, 160, 67, 0.35)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    color: "var(--success)",
    cursor: "pointer",
    flexShrink: 0,
  },
  terminalContainer: { flex: 1, overflow: "hidden" as const, padding: "14px 16px 16px" },
  interruptedSessionWrap: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  interruptedBanner: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: 7,
    minHeight: 38,
    padding: "4px 28px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
  },
  interruptedBannerIcon: {
    width: 18,
    height: 18,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--warning)",
    flexShrink: 0,
  },
  interruptedBannerBody: {
    minWidth: 0,
    flex: "1 1 180px",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  interruptedBannerTitle: {
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--text-primary)",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerActions: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap" as const,
    gap: 5,
    flexShrink: 0,
  },
  interruptedNoSessionPane: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 32px",
    color: "var(--text-hint)",
    fontSize: 13,
    lineHeight: 1.6,
    textAlign: "center" as const,
  },
  noSessionRecordPane: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: "20px",
    background: "var(--bg-panel)",
  },
  noSessionRecordCard: {
    maxWidth: 860,
    margin: "0 auto",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "var(--bg-card)",
    boxShadow: "inset 0 1px 0 color-mix(in srgb, #fff 7%, transparent)",
    overflow: "hidden",
  },
  noSessionRecordHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 16px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
  },
  noSessionRecordTitleBlock: {
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    gap: 2,
  },
  noSessionRecordTitle: {
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
  },
  noSessionRecordStatus: {
    color: "var(--text-muted)",
    fontSize: 11.5,
    lineHeight: 1.45,
  },
  noSessionRecordPromptLabel: {
    padding: "14px 16px 7px",
    color: "var(--text-hint)",
    fontSize: 10.5,
    fontWeight: 800,
    letterSpacing: 0.5,
    textTransform: "uppercase" as const,
  },
  noSessionRecordPrompt: {
    margin: "0 16px 16px",
    padding: "12px 13px",
    maxHeight: 360,
    overflow: "auto",
    border: "1px solid var(--border-dim)",
    borderRadius: 6,
    background: "var(--bg-root)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 12.5,
    lineHeight: 1.65,
    whiteSpace: "pre-wrap" as const,
    wordBreak: "break-word" as const,
  },
  interruptedPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
    background: "var(--bg-card)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedSecondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid rgba(46, 160, 67, 0.24)",
    color: "var(--success)",
    background: "rgba(46, 160, 67, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedDangerBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid rgba(248, 81, 73, 0.24)",
    color: "var(--danger)",
    background: "rgba(248, 81, 73, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
