import type React from "react";

const exportBtnBase = {
  display: "flex",
  alignItems: "center",
  gap: 5,
  padding: "4px 10px",
  background: "none",
  border: "1px solid var(--control-active-fg)",
  borderRadius: "var(--radius-sm)",
  fontSize: 12,
  color: "var(--control-active-fg)",
  flexShrink: 0,
} as const;

export const terminal = {
  runHeader: {
    padding: "16px 20px 8px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  },
  runMetaBranchRow: {
    marginTop: 4,
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 11,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  runMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
    fontSize: 12.5,
    color: "var(--text-primary)",
  },
  runAgentBadge: {
    minWidth: 0,
    maxWidth: "min(520px, 62vw)",
    display: "inline-flex",
    alignItems: "center",
    gap: 0,
    padding: "2px 9px",
    borderRadius: 999,
    border: "1px solid color-mix(in srgb, var(--accent) 24%, transparent)",
    background: "color-mix(in srgb, var(--accent) 18%, var(--bg-input) 82%)",
    color: "var(--text-primary)",
    boxShadow: "inset 0 1px 0 color-mix(in srgb, #fff 12%, transparent)",
    fontWeight: 700,
    lineHeight: 1.05,
  },
  runMetaText: {
    minWidth: 0,
    color: "var(--text-secondary)",
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  },
  cancelBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid var(--border-medium)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    color: "var(--text-muted)",
    cursor: "pointer",
    flexShrink: 0,
  },
  exportBtn: { ...exportBtnBase, cursor: "pointer" as const },
  exportBtnBusy: { ...exportBtnBase, cursor: "not-allowed" as const, opacity: 0.6 },
  resumeBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "var(--control-active-bg)",
    border: "1px solid var(--border-strong)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    color: "var(--control-active-fg)",
    cursor: "pointer",
    flexShrink: 0,
  },
  doneBtn: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    padding: "4px 10px",
    background: "none",
    border: "1px solid rgba(46, 160, 67, 0.35)",
    borderRadius: "var(--radius-sm)",
    fontSize: 12,
    color: "var(--success)",
    cursor: "pointer",
    flexShrink: 0,
  },
  /**
   * The run area under the meta row: live bars plus the terminal or the session
   * view. `position: relative` lives here so the dsh trajectory panel can cover
   * the whole area at `inset: 0` without covering the meta row's own controls or
   * the composer.
   */
  runBodyWrap: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    position: "relative" as const,
  },
  /**
   * 内边距的底色必须与终端自身一致,否则深色模式下 `--bg-panel`(rgba(12,15,19,.7))
   * 与终端的 `--terminal-bg`(rgba(6,8,10,.94))并排,四周会出现一圈明显更亮的边框。
   * 浅色/护眼模式同理,只是对比弱、不易察觉。
   */
  terminalContainer: {
    flex: 1,
    overflow: "hidden" as const,
    padding: "14px 16px 16px",
    background: "var(--terminal-bg)",
  },
  /**
   * omp 的输入框是 TUI 自己画在最后一行的,贴着容器底边会显得没有落脚点。
   * 额外垫高底部内边距,让输入框离窗口底边有一段留白。
   *
   * 只加**纵向**内边距:横向内边距会从 FitAddon 的可用宽度里扣,改了就改列数与
   * 折行位置,而 omp 的 TUI 会把状态栏和边框画到最后一列。
   */
  terminalContainerOmp: {
    flex: 1,
    overflow: "hidden" as const,
    padding: "14px 16px 28px",
    background: "var(--terminal-bg)",
  },
  interruptedSessionWrap: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  interruptedBanner: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap" as const,
    gap: 7,
    minHeight: 38,
    padding: "4px 28px",
    borderBottom: "1px solid var(--border-dim)",
    background: "var(--bg-subtle)",
  },
  interruptedBannerIcon: {
    width: 18,
    height: 18,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--warning)",
    flexShrink: 0,
  },
  interruptedBannerBody: {
    minWidth: 0,
    flex: "1 1 180px",
    display: "flex",
    alignItems: "baseline",
    gap: 8,
    flexWrap: "wrap" as const,
  },
  interruptedBannerTitle: {
    fontSize: 12.5,
    fontWeight: 650,
    color: "var(--text-primary)",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  interruptedBannerActions: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap" as const,
    gap: 5,
    flexShrink: 0,
  },
  interruptedNoSessionPane: {
    flex: 1,
    minHeight: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 32px",
    color: "var(--text-hint)",
    fontSize: 13,
    lineHeight: 1.6,
    textAlign: "center" as const,
  },
  interruptedPrimaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
    background: "var(--bg-card)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedSecondaryBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid rgba(46, 160, 67, 0.24)",
    color: "var(--success)",
    background: "rgba(46, 160, 67, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
  interruptedDangerBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    padding: "3px 8px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid rgba(248, 81, 73, 0.24)",
    color: "var(--danger)",
    background: "rgba(248, 81, 73, 0.055)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    minHeight: 26,
    whiteSpace: "nowrap" as const,
  },
} satisfies Record<string, React.CSSProperties>;
