import type React from "react";

export const usage = {
  usageDashboard: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  usageDashboardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 18,
    padding: "18px 22px 14px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  usageDashboardTitle: {
    margin: 0,
    color: "var(--text-primary)",
    fontSize: 18,
    fontWeight: 720,
    lineHeight: 1.3,
  },
  usageDashboardRange: {
    marginTop: 4,
    color: "var(--text-muted)",
    fontSize: 11.5,
    lineHeight: 1.4,
  },
  usageDashboardControls: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 8,
  },
  usageSegment: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    padding: 3,
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-md)",
    background: "var(--bg-subtle)",
  },
  usageDashboardScroll: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: "18px 22px 28px",
  },
  usageMetricGrid: {
    display: "grid",
    gap: 10,
  },
  usageMetricCard: {
    minWidth: 0,
    minHeight: 96,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "13px 14px",
    border: "1px solid var(--border-dim)",
    borderRadius: "var(--radius-sm)",
    background: "var(--bg-card)",
    boxShadow: "var(--shadow-xs)",
  },
  usageMetricHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  usageMetricLabel: {
    minWidth: 0,
    color: "var(--text-muted)",
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
  },
  usageMetricIcon: {
    width: 26,
    height: 26,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    borderRadius: "var(--radius-sm)",
    background: "var(--bg-subtle)",
    color: "var(--text-muted)",
  },
  usageMetricValue: {
    marginTop: 11,
    overflow: "hidden",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 20,
    fontWeight: 720,
    lineHeight: 1.2,
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  usageChartSection: {
    marginTop: 24,
    paddingTop: 18,
    borderTop: "1px solid var(--border-dim)",
  },
  usageSectionHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 16,
  },
  usageSectionTitle: {
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 700,
  },
  usageLegend: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 10,
  },
  usageLegendItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    color: "var(--text-muted)",
    fontSize: 10.5,
  },
  usageLegendSwatch: {
    width: 8,
    height: 8,
    borderRadius: 2,
    flexShrink: 0,
  },
  usageChartViewport: {
    overflowX: "auto",
    overflowY: "hidden",
    paddingBottom: 4,
  },
  usageChart: {
    height: 218,
    display: "flex",
    alignItems: "stretch",
    gap: 8,
  },
  usageChartAxis: {
    width: 46,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    paddingBottom: 24,
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    fontSize: 9.5,
    textAlign: "right",
  },
  usageChartPlot: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "stretch",
    gap: 6,
    borderBottom: "1px solid var(--border-medium)",
    backgroundImage: "linear-gradient(to bottom, var(--border-dim) 1px, transparent 1px)",
    backgroundSize: "100% 25%",
  },
  usageChartColumn: {
    minWidth: 14,
    flex: "1 1 0",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "stretch",
    position: "relative",
  },
  usageChartBar: {
    minHeight: 2,
    display: "flex",
    flexDirection: "column-reverse",
    overflow: "hidden",
    borderRadius: "4px 4px 1px 1px",
    background: "var(--bg-subtle)",
  },
  usageChartLabel: {
    height: 24,
    paddingTop: 6,
    overflow: "visible",
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    fontSize: 9,
    lineHeight: 1,
    textAlign: "center",
    whiteSpace: "nowrap",
  },
  usageCostNote: {
    marginTop: 14,
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    color: "var(--text-muted)",
    fontSize: 10.5,
    lineHeight: 1.5,
  },
  usageState: {
    minHeight: 280,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 24,
    color: "var(--text-muted)",
    fontSize: 12,
    textAlign: "center",
  },
  usageSourceSummary: {
    marginTop: 22,
    display: "grid",
    gap: 10,
    paddingTop: 18,
    borderTop: "1px solid var(--border-dim)",
  },
  usageSourceRow: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "80px minmax(110px, 1fr) auto auto",
    alignItems: "center",
    gap: 12,
    color: "var(--text-secondary)",
    fontSize: 11.5,
  },
  usageSourceTrack: {
    height: 6,
    overflow: "hidden",
    borderRadius: 3,
    background: "var(--bg-subtle)",
  },
  usageSourceFill: {
    height: "100%",
    minWidth: 2,
    borderRadius: 3,
  },
  usageSourceValue: {
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    fontSize: 10.5,
    textAlign: "right",
    whiteSpace: "nowrap",
  },
} satisfies Record<string, React.CSSProperties>;
