import type React from "react";

export const usage = {
  usageDashboard: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    background: "var(--bg-panel)",
  },
  usageDashboardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 18,
    padding: "16px 20px 13px",
    borderBottom: "1px solid var(--border-dim)",
    flexShrink: 0,
  },
  usageDashboardTitle: {
    margin: 0,
    color: "var(--text-primary)",
    fontSize: 18,
    fontWeight: 720,
    lineHeight: 1.3,
  },
  usageDashboardRange: {
    marginTop: 4,
    color: "var(--text-muted)",
    fontSize: 11.5,
    lineHeight: 1.4,
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  usageDashboardControls: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 8,
  },
  usageHeaderRight: {
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 12,
  },
  usageLiveStatus: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minHeight: 28,
    padding: "4px 9px",
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "color-mix(in srgb, var(--bg-card) 82%, var(--bg-subtle))",
    boxShadow: "inset 0 1px 0 color-mix(in srgb, white 5%, transparent)",
  },
  usageLiveText: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    color: "var(--text-hint)",
    fontSize: 9.5,
    lineHeight: 1.25,
    whiteSpace: "nowrap",
  },
  usageSegment: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    padding: 3,
    border: "1px solid var(--border-dim)",
    borderRadius: 8,
    background: "color-mix(in srgb, var(--bg-card) 78%, var(--bg-subtle))",
    boxShadow: "inset 0 1px 0 color-mix(in srgb, white 5%, transparent)",
  },
  usageDashboardScroll: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: "18px 22px 28px",
  },
  usageMetricGrid: {
    display: "grid",
    gap: 12,
  },
  usageMetricCard: {
    minWidth: 0,
    minHeight: 96,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "14px 15px",
    border: "1px solid color-mix(in srgb, var(--border-medium) 86%, transparent)",
    borderRadius: 8,
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--bg-card) 98%, white 2%), color-mix(in srgb, var(--bg-card) 92%, var(--bg-subtle) 8%))",
    boxShadow:
      "inset 0 1px 0 color-mix(in srgb, white 7%, transparent), 0 4px 12px color-mix(in srgb, var(--text-primary) 4%, transparent)",
  },
  usageMetricHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  usageMetricLabel: {
    minWidth: 0,
    color: "var(--text-muted)",
    fontSize: 11.5,
    fontWeight: 600,
    lineHeight: 1.3,
  },
  usageMetricIcon: {
    width: 26,
    height: 26,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    borderRadius: 6,
    background: "var(--bg-subtle)",
    color: "var(--text-muted)",
    boxShadow: "inset 0 0 0 1px color-mix(in srgb, currentColor 10%, transparent)",
  },
  usageMetricValue: {
    marginTop: 11,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontWeight: 720,
    lineHeight: 1.2,
    whiteSpace: "nowrap",
  },
  usageChartSection: {
    marginTop: 14,
    padding: "17px 18px 16px",
    border: "1px solid color-mix(in srgb, var(--border-medium) 90%, transparent)",
    borderRadius: 8,
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--bg-card) 98%, white 2%), var(--bg-card))",
    boxShadow:
      "inset 0 1px 0 color-mix(in srgb, white 7%, transparent), 0 6px 18px color-mix(in srgb, var(--text-primary) 5%, transparent)",
  },
  usageSectionHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 16,
  },
  usageSectionTitle: {
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    fontWeight: 700,
  },
  usageLegend: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 10,
  },
  usageLegendItem: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    color: "var(--text-muted)",
    fontSize: 10.5,
  },
  usageLegendSwatch: {
    width: 8,
    height: 8,
    borderRadius: 2,
    flexShrink: 0,
    boxShadow: "0 0 7px color-mix(in srgb, currentColor 45%, transparent)",
  },
  usageChartViewport: {
    position: "relative",
    overflowX: "auto",
    overflowY: "hidden",
    padding: "4px 2px 2px",
  },
  usageChart: {
    height: 254,
    display: "flex",
    alignItems: "stretch",
    gap: 10,
  },
  usageChartAxis: {
    width: 70,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "1px 0 30px",
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    fontSize: 9,
    textAlign: "right",
  },
  usageChartAxisTick: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 7,
    minHeight: 12,
    letterSpacing: 0.15,
  },
  usageChartPlot: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "stretch",
    gap: 10,
    position: "relative",
    isolation: "isolate",
    padding: "0 14px",
    borderBottom: "1px solid color-mix(in srgb, var(--accent) 32%, var(--border-medium))",
    borderLeft: "1px solid color-mix(in srgb, var(--accent) 18%, var(--border-dim))",
    borderRadius: "8px 8px 0 0",
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--usage-chart-input) 4%, transparent), transparent 42%)",
  },
  usageChartGrid: {
    position: "absolute",
    inset: "0 0 30px",
    zIndex: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    pointerEvents: "none",
  },
  usageChartColumn: {
    minWidth: 14,
    flex: "1 1 0",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
    position: "relative",
    outline: "none",
    zIndex: 1,
  },
  usageChartBar: {
    minHeight: 3,
    alignSelf: "center",
    display: "flex",
    flexDirection: "column-reverse",
    overflow: "hidden",
    borderRadius: "5px 5px 2px 2px",
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--bg-subtle) 86%, var(--accent) 14%), var(--bg-subtle))",
    boxShadow:
      "inset 0 0 0 1px color-mix(in srgb, var(--border-medium) 76%, transparent), 0 6px 16px color-mix(in srgb, var(--text-primary) 7%, transparent)",
  },
  usageChartBarValue: {
    position: "absolute",
    bottom: 238,
    padding: "3px 6px",
    border: "1px solid color-mix(in srgb, var(--accent) 28%, var(--border-dim))",
    borderRadius: 6,
    background: "color-mix(in srgb, var(--bg-card) 90%, transparent)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    fontSize: 9,
    fontWeight: 700,
    boxShadow: "0 4px 12px color-mix(in srgb, var(--text-primary) 8%, transparent)",
  },
  usageChartLabel: {
    height: 30,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 4,
    paddingTop: 7,
    overflow: "visible",
    color: "var(--text-hint)",
    fontFamily: "var(--font-mono)",
    fontSize: 9,
    lineHeight: 1,
    textAlign: "center",
    whiteSpace: "nowrap",
  },
  usageChartLabelActive: {
    color: "var(--text-primary)",
  },
  usageChartTooltip: {
    position: "absolute",
    top: 8,
    right: 10,
    width: 210,
    display: "flex",
    flexDirection: "column",
    gap: 7,
    padding: "10px 11px",
    border: "1px solid var(--border-medium)",
    borderRadius: 8,
    background: "color-mix(in srgb, var(--bg-card) 90%, transparent)",
    boxShadow:
      "0 18px 44px color-mix(in srgb, var(--text-primary) 14%, transparent), inset 0 1px 0 color-mix(in srgb, white 8%, transparent)",
    backdropFilter: "blur(18px)",
    color: "var(--text-secondary)",
    fontSize: 10.5,
    pointerEvents: "none",
  },
  usageChartTooltipHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingBottom: 7,
    borderBottom: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
  },
  usageChartTooltipRow: {
    display: "grid",
    gridTemplateColumns: "8px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 7,
  },
  usageChartTooltipTotal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: 7,
    borderTop: "1px solid var(--border-dim)",
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
  },
  usageCostNote: {
    marginTop: 14,
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    color: "var(--text-muted)",
    fontSize: 10.5,
    lineHeight: 1.5,
  },
  usageState: {
    minHeight: 280,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    padding: 24,
    color: "var(--text-muted)",
    fontSize: 12,
    textAlign: "center",
  },
  usageSourceSummary: {
    marginTop: 14,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    padding: 16,
    border: "1px solid color-mix(in srgb, var(--border-medium) 78%, transparent)",
    borderRadius: 8,
    background:
      "linear-gradient(180deg, color-mix(in srgb, var(--bg-card) 98%, white 2%), var(--bg-card))",
    boxShadow:
      "inset 0 1px 0 color-mix(in srgb, white 7%, transparent), 0 4px 12px color-mix(in srgb, var(--text-primary) 4%, transparent)",
  },
  usageSourceList: {
    display: "grid",
    gap: 12,
  },
  usageSourceRow: {
    minWidth: 0,
    display: "grid",
    gridTemplateColumns: "80px minmax(110px, 1fr) auto auto",
    alignItems: "center",
    gap: 12,
    color: "var(--text-secondary)",
    fontSize: 11.5,
  },
  usageSourceTrack: {
    height: 8,
    overflow: "hidden",
    borderRadius: 3,
    background: "var(--bg-subtle)",
  },
  usageSourceFill: {
    height: "100%",
    minWidth: 2,
    borderRadius: 3,
  },
  usageSourceValue: {
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono)",
    fontSize: 10.5,
    textAlign: "right",
    whiteSpace: "nowrap",
  },
} satisfies Record<string, React.CSSProperties>;
