//! 内建 oh-my-pi(omp)的托管 home(`PI_CODING_AGENT_DIR`)管理。
//!
//! Aeroric 不触碰用户自己的 `~/.omp`,而是托管 `~/.aeroric/agent-homes/omp`
//! (复用 `custom_agent_home` 的隔离目录机制;自定义 omp 档案为 `agent-homes/{id}`):
//! - `config.yml` 按需生成,首行带 `# AERORIC_OMP_CONFIG_VERSION=N`,版本升级时整体重写;
//! - `mcp.json` 首次写空骨架(Phase 5 由 `mcp.rs::build_omp_mcp_config` 填充),
//!   omp 启动时自动发现 home 层 `mcp.json`,无需 dsh 那样的 `--patch` 机制;
//! - omp 的 `PI_CODING_AGENT_DIR` 完整重定向 sessions/config/mcp/agent.db 等子路径。

use std::fs;
use std::path::PathBuf;

/// 受管 config.yml 内容版本;修改 `managed_config_content` 后必须递增。
const OMP_CONFIG_VERSION: u32 = 1;
const OMP_CONFIG_MARKER_PREFIX: &str = "# AERORIC_OMP_CONFIG_VERSION=";

pub(crate) struct OmpHomePaths {
    pub home: PathBuf,
    // Phase 4(配置面板读写 config.yml)消费。
    #[allow(dead_code)]
    pub config_path: PathBuf,
    // 实际写入走 mcp::omp_mcp_config_for_launch(home)(home.join("mcp.json")
    // 与本字段等价);保留字段是为 OmpHomePaths 的路径清单完整性。
    #[allow(dead_code)]
    pub mcp_path: PathBuf,
}

/// omp 族 agent 的托管 home:内建为 `agent-homes/omp`(与设置面板 config 默认
/// 路径 `omp_managed_home()` 同源;不能走 `custom_agent_home`,它会把保留 id
/// sanitize 成 `local_omp` 造成双轨),自定义 omp 档案为 `agent-homes/{id}`。
pub(crate) fn omp_home_for(agent: &str) -> Result<PathBuf, String> {
    if agent == "omp" {
        return crate::app_settings::omp_managed_home()
            .ok_or_else(|| "Cannot find home directory".to_string());
    }
    crate::app_settings::custom_agent_home(agent)
}

/// 托管 config.yml 的受管内容。只写已核实的 omp settings 键:
/// - `startup.quiet`:跳过欢迎屏与启动状态输出(rpc-ui 的 stdout 本就是协议通道,双保险);
/// - `compaction.asyncEnabled: false`:headless 下关闭后台投机压缩,避免非预期的 token 消耗。
fn managed_config_content() -> String {
    format!(
        "{prefix}{version}\n\
         # Generated by Aeroric for the managed oh-my-pi home.\n\
         # This file is rewritten whenever the version marker above changes.\n\
         startup:\n\
         \x20 quiet: true\n\
         compaction:\n\
         \x20 asyncEnabled: false\n",
        prefix = OMP_CONFIG_MARKER_PREFIX,
        version = OMP_CONFIG_VERSION,
    )
}

fn config_version_marker(content: &str) -> Option<u32> {
    content
        .lines()
        .find(|line| line.starts_with(OMP_CONFIG_MARKER_PREFIX))?
        .trim_start_matches(OMP_CONFIG_MARKER_PREFIX)
        .trim()
        .parse()
        .ok()
}

/// 幂等初始化 omp 族 agent 的托管 home。config.yml 缺失或版本标记低于当前版本时
/// (重新)生成;版本相等或更高时保留用户在受管文件里的后续改动。
pub(crate) fn ensure_omp_home_for(agent: &str) -> Result<OmpHomePaths, String> {
    let home = omp_home_for(agent)?;
    fs::create_dir_all(&home).map_err(|error| error.to_string())?;
    let config_path = home.join("config.yml");
    if !config_path.is_file() {
        crate::storage::atomic_write_private(&config_path, &managed_config_content())?;
    } else {
        let needs_rewrite = fs::read_to_string(&config_path)
            .ok()
            .and_then(|content| config_version_marker(&content))
            .map(|version| version < OMP_CONFIG_VERSION)
            // 已存在的文件没有版本标记时视为未知来源,不覆写。
            .unwrap_or(false);
        if needs_rewrite {
            crate::storage::atomic_write_private(&config_path, &managed_config_content())?;
        }
    }
    let mcp_path = home.join("mcp.json");
    if !mcp_path.is_file() {
        crate::storage::atomic_write_private(&mcp_path, "{\n}\n")?;
    }
    Ok(OmpHomePaths {
        home,
        config_path,
        mcp_path,
    })
}

/// omp thinking level 词表(与前端 `OMP_THINKING_LEVELS` 一致)。
pub(crate) fn is_valid_omp_thinking_level(effort: &str) -> bool {
    matches!(
        effort,
        "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max"
    )
}

const OMP_DEFAULT_THINKING_KEY: &str = "defaultThinkingLevel:";

/// 从 config.yml 内容解析 `defaultThinkingLevel`(omp schema 默认 "high",
/// 缺键时返回 None 由调用方补默认)。纯函数,便于测试。
fn read_omp_effort_from_config(content: &str) -> Option<String> {
    for line in content.lines() {
        // 只认根级键(无缩进),避免命中注释或嵌套块里的同名键。
        let Some(value) = line.strip_prefix(OMP_DEFAULT_THINKING_KEY) else {
            continue;
        };
        let value = value.trim().trim_matches(['"', '\'']);
        return is_valid_omp_thinking_level(value).then(|| value.to_string());
    }
    None
}

/// 在 config.yml 内容中行级替换 `defaultThinkingLevel`,缺失则追加。
/// 纯函数,便于测试。
fn apply_omp_effort_to_config(content: &str, effort: &str) -> String {
    let mut replaced = false;
    let mut lines: Vec<String> = content
        .lines()
        .map(|line| {
            if !replaced && line.starts_with(OMP_DEFAULT_THINKING_KEY) {
                replaced = true;
                format!("{OMP_DEFAULT_THINKING_KEY} {effort}")
            } else {
                line.to_string()
            }
        })
        .collect();
    if !replaced {
        lines.push(format!("{OMP_DEFAULT_THINKING_KEY} {effort}"));
    }
    let mut updated = lines.join("\n");
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated
}

/// 读取托管 config.yml 的 `defaultThinkingLevel`(omp schema 默认 "high")。
pub(crate) fn read_omp_reasoning_effort(agent: &str) -> Option<String> {
    let home = omp_home_for(agent).ok()?;
    let content = fs::read_to_string(home.join("config.yml")).ok()?;
    read_omp_effort_from_config(&content)
}

/// 更新托管 config.yml 的 `defaultThinkingLevel`(设置面板的 omp 默认思考档)。
pub(crate) fn update_omp_reasoning_effort(agent: &str, effort: &str) -> Result<(), String> {
    let effort = effort.trim();
    if !is_valid_omp_thinking_level(effort) {
        return Err(format!("Invalid omp thinking level: {effort}"));
    }
    let paths = ensure_omp_home_for(agent)?;
    let content = fs::read_to_string(&paths.config_path).unwrap_or_default();
    let updated = apply_omp_effort_to_config(&content, effort);
    crate::storage::atomic_write_private(&paths.config_path, &updated)
}

/// 每次启动 omp 进程都要注入的环境变量(见计划 §2.2)。
pub(crate) fn omp_agent_env(home: &std::path::Path) -> Vec<(String, String)> {
    vec![
        (
            "PI_CODING_AGENT_DIR".to_string(),
            home.to_string_lossy().into_owned(),
        ),
        ("OMP_APP_NAME".to_string(), "aeroric".to_string()),
        ("OMP_SKIP_SETUP".to_string(), "1".to_string()),
        ("PI_AUTO_QA".to_string(), "0".to_string()),
        ("NO_COLOR".to_string(), "1".to_string()),
        ("OTEL_SDK_DISABLED".to_string(), "true".to_string()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_marker_parses_version() {
        assert_eq!(
            config_version_marker("# AERORIC_OMP_CONFIG_VERSION=1\nstartup:\n  quiet: true\n"),
            Some(1)
        );
        assert_eq!(config_version_marker("startup:\n  quiet: true\n"), None);
    }

    #[test]
    fn managed_config_carries_current_marker_and_verified_keys() {
        let content = managed_config_content();
        assert_eq!(config_version_marker(&content), Some(OMP_CONFIG_VERSION));
        assert!(content.contains("startup:\n  quiet: true"));
        assert!(content.contains("compaction:\n  asyncEnabled: false"));
    }

    #[test]
    fn omp_thinking_level_validation_rejects_unknown_levels() {
        assert!(is_valid_omp_thinking_level("off"));
        assert!(is_valid_omp_thinking_level("xhigh"));
        assert!(is_valid_omp_thinking_level("max"));
        assert!(!is_valid_omp_thinking_level("ultra"));
        assert!(!is_valid_omp_thinking_level("auto"));
        assert!(!is_valid_omp_thinking_level(""));
    }

    #[test]
    fn omp_effort_config_roundtrip_replaces_root_key_only() {
        let base = managed_config_content();
        // 缺键时读到 None,追加后能读回。
        assert_eq!(read_omp_effort_from_config(&base), None);
        let updated = apply_omp_effort_to_config(&base, "xhigh");
        assert_eq!(
            read_omp_effort_from_config(&updated).as_deref(),
            Some("xhigh")
        );
        // 受管标记行不受影响。
        assert!(updated.starts_with(OMP_CONFIG_MARKER_PREFIX));
        // 再次更新走替换而不是追加。
        let updated_again = apply_omp_effort_to_config(&updated, "low");
        assert_eq!(updated_again.matches("defaultThinkingLevel").count(), 1);
        assert_eq!(
            read_omp_effort_from_config(&updated_again).as_deref(),
            Some("low")
        );
        // 注释行与嵌套块里的同名键不参与解析。
        let tricky = format!(
            "# {key} max\ncompaction:\n  {key} off\n{key} high\n",
            key = OMP_DEFAULT_THINKING_KEY
        );
        assert_eq!(
            read_omp_effort_from_config(&tricky).as_deref(),
            Some("high")
        );
        // 非法值视为未设置。
        assert_eq!(
            read_omp_effort_from_config("defaultThinkingLevel: ultra"),
            None
        );
        // 更新以换行结尾,保持 YAML 合法。
        assert!(apply_omp_effort_to_config(&base, "off").ends_with('\n'));
    }

    #[test]
    fn agent_env_redirects_agent_dir_and_labels_app() {
        let env = omp_agent_env(std::path::Path::new("/tmp/omp-home"));
        let get = |key: &str| env.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone());
        assert_eq!(get("PI_CODING_AGENT_DIR").as_deref(), Some("/tmp/omp-home"));
        assert_eq!(get("OMP_APP_NAME").as_deref(), Some("aeroric"));
        assert!(get("OMP_SKIP_SETUP").is_some());
    }
}
