//! 内建 oh-my-pi(omp)的托管 home(`PI_CODING_AGENT_DIR`)管理。
//!
//! Aeroric 不触碰用户自己的 `~/.omp`,而是托管 `~/.aeroric/agent-homes/omp`
//! (复用 `custom_agent_home` 的隔离目录机制;自定义 omp 档案为 `agent-homes/{id}`):
//! - `config.yml` 按需生成,首行带 `# AERORIC_OMP_CONFIG_VERSION=N`,版本升级时整体重写;
//! - `mcp.json` 首次写空骨架(Phase 5 由 `mcp.rs::build_omp_mcp_config` 填充),
//!   omp 启动时自动发现 home 层 `mcp.json`,无需 dsh 那样的 `--patch` 机制;
//! - omp 的 `PI_CODING_AGENT_DIR` 完整重定向 sessions/config/mcp/agent.db 等子路径。

use std::fs;
use std::path::PathBuf;

/// 受管 config.yml 内容版本;修改 `managed_config_content` 后必须递增。
const OMP_CONFIG_VERSION: u32 = 1;
const OMP_CONFIG_MARKER_PREFIX: &str = "# AERORIC_OMP_CONFIG_VERSION=";

pub(crate) struct OmpHomePaths {
    pub home: PathBuf,
    // Phase 4(配置面板读写 config.yml)/ Phase 5(mcp.json 生成)消费。
    #[allow(dead_code)]
    pub config_path: PathBuf,
    #[allow(dead_code)]
    pub mcp_path: PathBuf,
}

/// omp 族 agent 的托管 home:内建为 `agent-homes/omp`(与设置面板 config 默认
/// 路径 `omp_managed_home()` 同源;不能走 `custom_agent_home`,它会把保留 id
/// sanitize 成 `local_omp` 造成双轨),自定义 omp 档案为 `agent-homes/{id}`。
pub(crate) fn omp_home_for(agent: &str) -> Result<PathBuf, String> {
    if agent == "omp" {
        return crate::app_settings::omp_managed_home()
            .ok_or_else(|| "Cannot find home directory".to_string());
    }
    crate::app_settings::custom_agent_home(agent)
}

/// 托管 config.yml 的受管内容。只写已核实的 omp settings 键:
/// - `startup.quiet`:跳过欢迎屏与启动状态输出(rpc-ui 的 stdout 本就是协议通道,双保险);
/// - `compaction.asyncEnabled: false`:headless 下关闭后台投机压缩,避免非预期的 token 消耗。
fn managed_config_content() -> String {
    format!(
        "{prefix}{version}\n\
         # Generated by Aeroric for the managed oh-my-pi home.\n\
         # This file is rewritten whenever the version marker above changes.\n\
         startup:\n\
         \x20 quiet: true\n\
         compaction:\n\
         \x20 asyncEnabled: false\n",
        prefix = OMP_CONFIG_MARKER_PREFIX,
        version = OMP_CONFIG_VERSION,
    )
}

fn config_version_marker(content: &str) -> Option<u32> {
    content
        .lines()
        .find(|line| line.starts_with(OMP_CONFIG_MARKER_PREFIX))?
        .trim_start_matches(OMP_CONFIG_MARKER_PREFIX)
        .trim()
        .parse()
        .ok()
}

/// 幂等初始化 omp 族 agent 的托管 home。config.yml 缺失或版本标记低于当前版本时
/// (重新)生成;版本相等或更高时保留用户在受管文件里的后续改动。
pub(crate) fn ensure_omp_home_for(agent: &str) -> Result<OmpHomePaths, String> {
    let home = omp_home_for(agent)?;
    fs::create_dir_all(&home).map_err(|error| error.to_string())?;
    let config_path = home.join("config.yml");
    if !config_path.is_file() {
        crate::storage::atomic_write_private(&config_path, &managed_config_content())?;
    } else {
        let needs_rewrite = fs::read_to_string(&config_path)
            .ok()
            .and_then(|content| config_version_marker(&content))
            .map(|version| version < OMP_CONFIG_VERSION)
            // 已存在的文件没有版本标记时视为未知来源,不覆写。
            .unwrap_or(false);
        if needs_rewrite {
            crate::storage::atomic_write_private(&config_path, &managed_config_content())?;
        }
    }
    let mcp_path = home.join("mcp.json");
    if !mcp_path.is_file() {
        crate::storage::atomic_write_private(&mcp_path, "{\n}\n")?;
    }
    Ok(OmpHomePaths {
        home,
        config_path,
        mcp_path,
    })
}

/// 每次启动 omp 进程都要注入的环境变量(见计划 §2.2)。
pub(crate) fn omp_agent_env(home: &std::path::Path) -> Vec<(String, String)> {
    vec![
        (
            "PI_CODING_AGENT_DIR".to_string(),
            home.to_string_lossy().into_owned(),
        ),
        ("OMP_APP_NAME".to_string(), "aeroric".to_string()),
        ("OMP_SKIP_SETUP".to_string(), "1".to_string()),
        ("PI_AUTO_QA".to_string(), "0".to_string()),
        ("NO_COLOR".to_string(), "1".to_string()),
        ("OTEL_SDK_DISABLED".to_string(), "true".to_string()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_marker_parses_version() {
        assert_eq!(
            config_version_marker("# AERORIC_OMP_CONFIG_VERSION=1\nstartup:\n  quiet: true\n"),
            Some(1)
        );
        assert_eq!(config_version_marker("startup:\n  quiet: true\n"), None);
    }

    #[test]
    fn managed_config_carries_current_marker_and_verified_keys() {
        let content = managed_config_content();
        assert_eq!(config_version_marker(&content), Some(OMP_CONFIG_VERSION));
        assert!(content.contains("startup:\n  quiet: true"));
        assert!(content.contains("compaction:\n  asyncEnabled: false"));
    }

    #[test]
    fn agent_env_redirects_agent_dir_and_labels_app() {
        let env = omp_agent_env(std::path::Path::new("/tmp/omp-home"));
        let get = |key: &str| env.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone());
        assert_eq!(get("PI_CODING_AGENT_DIR").as_deref(), Some("/tmp/omp-home"));
        assert_eq!(get("OMP_APP_NAME").as_deref(), Some("aeroric"));
        assert!(get("OMP_SKIP_SETUP").is_some());
    }
}
