//! 内建 oh-my-pi(omp)的托管 home(`PI_CODING_AGENT_DIR`)管理。
//!
//! Aeroric 不触碰用户自己的 `~/.omp`,而是托管 `~/.aeroric/agent-homes/omp`
//! (复用 `custom_agent_home` 的隔离目录机制;自定义 omp 档案为 `agent-homes/{id}`):
//! - `config.yml` 按需生成,首行带 `# AERORIC_OMP_CONFIG_VERSION=N`,版本升级时整体重写;
//! - `mcp.json` 首次写空骨架(Phase 5 由 `mcp.rs::build_omp_mcp_config` 填充),
//!   omp 启动时自动发现 home 层 `mcp.json`,无需 dsh 那样的 `--patch` 机制;
//! - omp 的 `PI_CODING_AGENT_DIR` 完整重定向 sessions/config/mcp/agent.db 等子路径。

use std::fs;
use std::path::PathBuf;

/// 受管 config.yml / hook 脚本的内容版本;修改任一受管文件后必须递增。
const OMP_CONFIG_VERSION: u32 = 2;
const OMP_CONFIG_MARKER_PREFIX: &str = "# AERORIC_OMP_CONFIG_VERSION=";

pub(crate) struct OmpHomePaths {
    pub home: PathBuf,
    // Phase 4(配置面板读写 config.yml)消费。
    #[allow(dead_code)]
    pub config_path: PathBuf,
    // 实际写入走 mcp::omp_mcp_config_for_launch(home)(home.join("mcp.json")
    // 与本字段等价);保留字段是为 OmpHomePaths 的路径清单完整性。
    #[allow(dead_code)]
    pub mcp_path: PathBuf,
}

/// omp 族 agent 的托管 home:内建为 `agent-homes/omp`(与设置面板 config 默认
/// 路径 `omp_managed_home()` 同源;不能走 `custom_agent_home`,它会把保留 id
/// sanitize 成 `local_omp` 造成双轨),自定义 omp 档案为 `agent-homes/{id}`。
pub(crate) fn omp_home_for(agent: &str) -> Result<PathBuf, String> {
    if agent == "omp" {
        return crate::app_settings::omp_managed_home()
            .ok_or_else(|| "Cannot find home directory".to_string());
    }
    crate::app_settings::custom_agent_home(agent)
}

/// 装进托管 home 的 omp hook(`hooks/post/*.js`)。
///
/// 扩展名**必须**是 `.js` 或 `.ts`:hook 路径经 `loadCapability<Hook>` 拿到后,
/// 还要过 `extensibility/extensions/loader.ts:702` 的 `isExtensionFile`,而它只
/// 认这两个后缀(:511-513)。`.mjs` 会被静默丢弃 —— 目录扫描能看到文件、hook 却
/// 永远不加载,任务因此永远停在 running。
///
/// 文件名的 `*` 是 omp 的 tool 通配(`discovery/builtin.ts:707` 按 basename 去
/// 扩展名解析);实际的事件订阅走 `pi.on`,与文件名里的 tool 无关。
const OMP_HOOK_SCRIPT: &str = include_str!("aeroric-omp-hook.js");

/// 托管 config.yml 的受管内容。只写已核实的 omp settings 键:
/// - `compaction.asyncEnabled: false`:关闭后台投机压缩,避免非预期的 token 消耗。
///
/// 刻意**不写** `startup.quiet`:omp 现在跑在真 PTY 里的原生交互式 TUI,
/// quiet 会压掉 splash、MCP/LSP 连接提示与 model-scope 通知,而这些正是"在命令行
/// 里直接敲 omp"该看到的东西。omp 原生默认即 false。
fn managed_config_content() -> String {
    format!(
        "{prefix}{version}\n\
         # Generated by Aeroric for the managed oh-my-pi home.\n\
         # This file is rewritten whenever the version marker above changes.\n\
         compaction:\n\
         \x20 asyncEnabled: false\n",
        prefix = OMP_CONFIG_MARKER_PREFIX,
        version = OMP_CONFIG_VERSION,
    )
}

fn config_version_marker(content: &str) -> Option<u32> {
    content
        .lines()
        .find(|line| line.starts_with(OMP_CONFIG_MARKER_PREFIX))?
        .trim_start_matches(OMP_CONFIG_MARKER_PREFIX)
        .trim()
        .parse()
        .ok()
}

/// 幂等初始化 omp 族 agent 的托管 home。config.yml 缺失或版本标记低于当前版本时
/// (重新)生成;版本相等或更高时保留用户在受管文件里的后续改动。hook 脚本没有
/// 版本标记可放(它是 omp 要 import 的 ESM 模块),改为内容比对后按需重写 ——
/// 用户没有理由手改 Aeroric 托管的 hook,而漏更新会让状态机静默失效。
pub(crate) fn ensure_omp_home_for(agent: &str) -> Result<OmpHomePaths, String> {
    let home = omp_home_for(agent)?;
    fs::create_dir_all(&home).map_err(|error| error.to_string())?;
    let config_path = home.join("config.yml");
    if !config_path.is_file() {
        crate::storage::atomic_write_private(&config_path, &managed_config_content())?;
    } else {
        let needs_rewrite = fs::read_to_string(&config_path)
            .ok()
            .and_then(|content| config_version_marker(&content))
            .map(|version| version < OMP_CONFIG_VERSION)
            // 已存在的文件没有版本标记时视为未知来源,不覆写。
            .unwrap_or(false);
        if needs_rewrite {
            crate::storage::atomic_write_private(&config_path, &managed_config_content())?;
        }
    }
    let mcp_path = home.join("mcp.json");
    if !mcp_path.is_file() {
        crate::storage::atomic_write_private(&mcp_path, "{\n}\n")?;
    }
    // omp 的 hook 发现路径:`<PI_CODING_AGENT_DIR>/hooks/{pre,post}/`
    // (`discovery/builtin.ts::loadHooks`)。装在 post/ 下,文件名 `*` 表示对所有
    // tool 生效;真正的事件订阅在脚本里用 `pi.on` 完成。
    let hook_dir = home.join("hooks").join("post");
    fs::create_dir_all(&hook_dir).map_err(|error| error.to_string())?;
    let hook_path = hook_dir.join("*.js");
    let hook_current = fs::read_to_string(&hook_path).ok();
    if hook_current.as_deref() != Some(OMP_HOOK_SCRIPT) {
        crate::storage::atomic_write_private(&hook_path, OMP_HOOK_SCRIPT)?;
    }
    // 1.4.7 开发期短暂装过 `*.mjs`;它过不了 isExtensionFile 但会留在目录里,
    // 删掉免得日后排查时误以为 hook 已生效。
    let _ = fs::remove_file(hook_dir.join("*.mjs"));
    Ok(OmpHomePaths {
        home,
        config_path,
        mcp_path,
    })
}

/// omp thinking level 词表(与前端 `OMP_THINKING_LEVELS` 一致)。
pub(crate) fn is_valid_omp_thinking_level(effort: &str) -> bool {
    matches!(
        effort,
        "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max"
    )
}

const OMP_DEFAULT_THINKING_KEY: &str = "defaultThinkingLevel:";

/// 从 config.yml 内容解析 `defaultThinkingLevel`(omp schema 默认 "high",
/// 缺键时返回 None 由调用方补默认)。纯函数,便于测试。
fn read_omp_effort_from_config(content: &str) -> Option<String> {
    for line in content.lines() {
        // 只认根级键(无缩进),避免命中注释或嵌套块里的同名键。
        let Some(value) = line.strip_prefix(OMP_DEFAULT_THINKING_KEY) else {
            continue;
        };
        let value = value.trim().trim_matches(['"', '\'']);
        return is_valid_omp_thinking_level(value).then(|| value.to_string());
    }
    None
}

/// 在 config.yml 内容中行级替换 `defaultThinkingLevel`,缺失则追加。
/// 纯函数,便于测试。
fn apply_omp_effort_to_config(content: &str, effort: &str) -> String {
    let mut replaced = false;
    let mut lines: Vec<String> = content
        .lines()
        .map(|line| {
            if !replaced && line.starts_with(OMP_DEFAULT_THINKING_KEY) {
                replaced = true;
                format!("{OMP_DEFAULT_THINKING_KEY} {effort}")
            } else {
                line.to_string()
            }
        })
        .collect();
    if !replaced {
        lines.push(format!("{OMP_DEFAULT_THINKING_KEY} {effort}"));
    }
    let mut updated = lines.join("\n");
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated
}

/// 读取托管 config.yml 的 `defaultThinkingLevel`(omp schema 默认 "high")。
pub(crate) fn read_omp_reasoning_effort(agent: &str) -> Option<String> {
    let home = omp_home_for(agent).ok()?;
    let content = fs::read_to_string(home.join("config.yml")).ok()?;
    read_omp_effort_from_config(&content)
}

/// 更新托管 config.yml 的 `defaultThinkingLevel`(设置面板的 omp 默认思考档)。
pub(crate) fn update_omp_reasoning_effort(agent: &str, effort: &str) -> Result<(), String> {
    let effort = effort.trim();
    if !is_valid_omp_thinking_level(effort) {
        return Err(format!("Invalid omp thinking level: {effort}"));
    }
    let paths = ensure_omp_home_for(agent)?;
    let content = fs::read_to_string(&paths.config_path).unwrap_or_default();
    let updated = apply_omp_effort_to_config(&content, effort);
    crate::storage::atomic_write_private(&paths.config_path, &updated)
}

/// 保存 omp 族配置的默认思考档(写入托管 config.yml 的 `defaultThinkingLevel`)。
#[tauri::command]
pub async fn update_omp_thinking_level(agent: String, effort: String) -> Result<(), String> {
    tokio::task::spawn_blocking(move || update_omp_reasoning_effort(&agent, &effort))
        .await
        .map_err(|error| error.to_string())?
}

/// 读取 omp 族配置的默认思考档(未设置时为 None,前端回退 omp 默认 high)。
#[tauri::command]
pub async fn get_omp_thinking_level(agent: String) -> Result<Option<String>, String> {
    tokio::task::spawn_blocking(move || {
        Ok::<Option<String>, String>(read_omp_reasoning_effort(&agent))
    })
    .await
    .map_err(|error| error.to_string())?
}

/// YAML 双引号字符串字面量(转义反斜杠与双引号)。
fn yaml_double_quoted(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}

/// 读取既有 models.yml 里的 provider api 协议(缺省 openai-completions)。
/// profile 不存协议,更新档案时以此保留用户原选。
pub(crate) fn read_omp_api_protocol(home: &std::path::Path) -> String {
    let Ok(content) = fs::read_to_string(home.join("models.yml")) else {
        return "openai-completions".to_string();
    };
    for line in content.lines() {
        let trimmed = line.trim_start();
        if let Some(value) = trimmed.strip_prefix("api:") {
            let value = value.trim().trim_matches(['"', '\'']);
            if matches!(
                value,
                "openai-completions" | "openai-responses" | "anthropic-messages"
            ) {
                return value.to_string();
            }
        }
    }
    "openai-completions".to_string()
}

/// 为自定义 omp 档案写 models.yml:provider `aeroric` 指向用户给的 base_url,
/// 携带 api key 与所选协议(openai-completions/openai-responses/anthropic-messages,
/// 与 omp 的 `Api` 取值一致)。
///
/// base_url 留空表示"改用 omp 自带凭据",此时必须把既有 models.yml **删掉**而不是
/// 原地保留:编辑档案时清空 Base URL 会走到这里,只 return Ok 的话文件里上一次写入的
/// `baseUrl` 与明文 `apiKey` 仍在磁盘上,omp 每次启动都照旧读它 —— 用户以为已经摘掉的
/// 第三方网关和密钥其实还在生效。
pub(crate) fn write_custom_provider_models_yml(
    home: &std::path::Path,
    base_url: &str,
    api_key: &str,
    api: &str,
    models: &[String],
) -> Result<(), String> {
    let models_path = home.join("models.yml");
    if base_url.trim().is_empty() {
        return match fs::remove_file(&models_path) {
            Ok(()) => Ok(()),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
            Err(error) => Err(error.to_string()),
        };
    }
    if !matches!(
        api,
        "openai-completions" | "openai-responses" | "anthropic-messages"
    ) {
        return Err(format!("Unsupported omp api protocol: {api}"));
    }
    let mut out = String::from(
        "# Generated by Aeroric for this managed oh-my-pi profile.\nproviders:\n  aeroric:\n",
    );
    out.push_str(&format!("    baseUrl: {}\n", yaml_double_quoted(base_url)));
    if !api_key.trim().is_empty() {
        out.push_str(&format!("    apiKey: {}\n", yaml_double_quoted(api_key)));
    }
    out.push_str(&format!("    api: {}\n", yaml_double_quoted(api)));
    out.push_str("    models:\n");
    for model in models {
        let id = model.trim();
        if id.is_empty() {
            continue;
        }
        out.push_str(&format!("      - id: {}\n", yaml_double_quoted(id)));
    }
    crate::storage::atomic_write_private(&models_path, &out)
}

/// 每次启动 omp 进程都要注入的环境变量。
///
/// 刻意**不含** `NO_COLOR`:omp 现在跑在真 PTY 里,必须出彩色才能与"在命令行里
/// 直接敲 omp"一致;颜色相关变量统一由 `pty::setup_env` 给
/// (TERM/COLORTERM/FORCE_COLOR)。
/// `OMP_SKIP_SETUP=1` 不可删:否则首启会在 PTY 里弹出交互式 setup wizard。
pub(crate) fn omp_agent_env(home: &std::path::Path) -> Vec<(String, String)> {
    vec![
        (
            "PI_CODING_AGENT_DIR".to_string(),
            home.to_string_lossy().into_owned(),
        ),
        ("OMP_APP_NAME".to_string(), "aeroric".to_string()),
        ("OMP_SKIP_SETUP".to_string(), "1".to_string()),
        ("PI_AUTO_QA".to_string(), "0".to_string()),
        ("OTEL_SDK_DISABLED".to_string(), "true".to_string()),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_marker_parses_version() {
        assert_eq!(
            config_version_marker("# AERORIC_OMP_CONFIG_VERSION=1\nstartup:\n  quiet: true\n"),
            Some(1)
        );
        assert_eq!(config_version_marker("startup:\n  quiet: true\n"), None);
    }

    /// omp 跑在真 PTY 里的原生 TUI,受管 config 不得压制启动输出:`startup.quiet`
    /// 会吞掉 splash、MCP/LSP 连接提示与 model-scope 通知,而那些正是"命令行里直接
    /// 敲 omp"该看到的东西。这条断言防它被顺手加回来。
    #[test]
    fn managed_config_carries_current_marker_and_leaves_startup_output_alone() {
        let content = managed_config_content();
        assert_eq!(config_version_marker(&content), Some(OMP_CONFIG_VERSION));
        assert!(content.contains("compaction:\n  asyncEnabled: false"));
        assert!(
            !content.contains("quiet"),
            "受管 config 不能压制 omp 的启动输出:{content}"
        );
    }

    /// PTY 里必须出彩色,否则与命令行直接跑 omp 的外观必然不同。
    #[test]
    fn agent_env_never_suppresses_color() {
        let env = omp_agent_env(std::path::Path::new("/tmp/omp-home"));
        assert!(
            !env.iter().any(|(key, _)| key == "NO_COLOR"),
            "omp 在 PTY 里跑,NO_COLOR 会让原生 TUI 掉色"
        );
    }

    /// hook 是状态机的唯一来源:没有它任务会永远停在 running。
    #[test]
    fn bundled_hook_subscribes_agent_lifecycle_and_guards_on_task_env() {
        assert!(OMP_HOOK_SCRIPT.contains("export default"));
        assert!(OMP_HOOK_SCRIPT.contains("pi.on(\"agent_start\""));
        assert!(OMP_HOOK_SCRIPT.contains("pi.on(\"agent_end\""));
        assert!(OMP_HOOK_SCRIPT.contains("AERORIC_TASK_ID"));
        assert!(OMP_HOOK_SCRIPT.contains("AERORIC_EVENT_DIR"));
        // willContinue 是自动续跑,不是用户可见终态。
        assert!(OMP_HOOK_SCRIPT.contains("willContinue"));
    }

    #[test]
    fn omp_thinking_level_validation_rejects_unknown_levels() {
        assert!(is_valid_omp_thinking_level("off"));
        assert!(is_valid_omp_thinking_level("xhigh"));
        assert!(is_valid_omp_thinking_level("max"));
        assert!(!is_valid_omp_thinking_level("ultra"));
        assert!(!is_valid_omp_thinking_level("auto"));
        assert!(!is_valid_omp_thinking_level(""));
    }

    /// 清空 Base URL 必须让 models.yml 消失,而不是留着上一次的网关与明文密钥。
    ///
    /// 编辑档案时清空 Base URL 会以空串走到 `write_custom_provider_models_yml`。
    /// 早先的实现只 `return Ok(())`,文件原地保留 —— 设置面板显示已无自定义网关,
    /// 而 omp 每次启动仍读到旧的 `baseUrl` + `apiKey`,继续把请求发往用户以为
    /// 已经摘掉的第三方网关。
    #[test]
    fn clearing_base_url_removes_the_stale_models_yml_and_its_api_key() {
        let home =
            std::env::temp_dir().join(format!("aeroric-omp-models-{}", uuid::Uuid::new_v4()));
        fs::create_dir_all(&home).unwrap();
        let models_path = home.join("models.yml");

        write_custom_provider_models_yml(
            &home,
            "https://gateway.example.com/v1",
            "sk-should-not-survive",
            "openai-completions",
            &["demo-model".to_string()],
        )
        .unwrap();
        let written = fs::read_to_string(&models_path).unwrap();
        assert!(written.contains("gateway.example.com"));
        assert!(written.contains("sk-should-not-survive"));

        // 清空 Base URL:文件必须被删掉,密钥不能留在磁盘上。
        write_custom_provider_models_yml(&home, "", "", "openai-completions", &[]).unwrap();
        assert!(
            !models_path.exists(),
            "清空 base_url 后 models.yml 仍在,旧网关与明文密钥会继续生效"
        );

        // 幂等:已经没有文件时再清一次不报错。
        write_custom_provider_models_yml(&home, "   ", "", "openai-completions", &[]).unwrap();

        let _ = fs::remove_dir_all(home);
    }

    #[test]
    fn omp_effort_config_roundtrip_replaces_root_key_only() {
        let base = managed_config_content();
        // 缺键时读到 None,追加后能读回。
        assert_eq!(read_omp_effort_from_config(&base), None);
        let updated = apply_omp_effort_to_config(&base, "xhigh");
        assert_eq!(
            read_omp_effort_from_config(&updated).as_deref(),
            Some("xhigh")
        );
        // 受管标记行不受影响。
        assert!(updated.starts_with(OMP_CONFIG_MARKER_PREFIX));
        // 再次更新走替换而不是追加。
        let updated_again = apply_omp_effort_to_config(&updated, "low");
        assert_eq!(updated_again.matches("defaultThinkingLevel").count(), 1);
        assert_eq!(
            read_omp_effort_from_config(&updated_again).as_deref(),
            Some("low")
        );
        // 注释行与嵌套块里的同名键不参与解析。
        let tricky = format!(
            "# {key} max\ncompaction:\n  {key} off\n{key} high\n",
            key = OMP_DEFAULT_THINKING_KEY
        );
        assert_eq!(
            read_omp_effort_from_config(&tricky).as_deref(),
            Some("high")
        );
        // 非法值视为未设置。
        assert_eq!(
            read_omp_effort_from_config("defaultThinkingLevel: ultra"),
            None
        );
        // 更新以换行结尾,保持 YAML 合法。
        assert!(apply_omp_effort_to_config(&base, "off").ends_with('\n'));
    }

    #[test]
    fn agent_env_redirects_agent_dir_and_labels_app() {
        let env = omp_agent_env(std::path::Path::new("/tmp/omp-home"));
        let get = |key: &str| env.iter().find(|(k, _)| k == key).map(|(_, v)| v.clone());
        assert_eq!(get("PI_CODING_AGENT_DIR").as_deref(), Some("/tmp/omp-home"));
        assert_eq!(get("OMP_APP_NAME").as_deref(), Some("aeroric"));
        assert!(get("OMP_SKIP_SETUP").is_some());
    }
}
