/**
 * DeepSeek Harness protocol snapshot.
 *
 * This is intentionally a small, generated-style compatibility boundary.  The
 * official Harness remains the runtime authority; Aeroric uses this snapshot
 * to advertise which wire surfaces it knows how to bridge and to fail soft
 * when a newer Harness adds a frame instead of silently mis-rendering it.
 *
 * Pinned to c291e7961a (0.1.5-rc.2).  Between the previous pin (b150a551b8,
 * 0.1.1-rc.2) and this one, upstream retired the apiproxy unary domain
 * (`refactor(apiproxy): retire migrated unary routes`, ce3391e280) and
 * replaced it with Typert `@Remote` controllers.  Method names below use the
 * historical `namespace.method` spelling so the allowlist in
 * `invoke_dsh_remote` stays dotted; the HTTP path those remotes actually
 * answer is `/api/{namespace}/{method}` (slash).  Named wrappers in
 * `dsh_webui.rs` call those Typert remotes through the JSON RPC gateway
 * (`payload.args`); DSH-5 migrated them and DSH-14 migrated the downlink.
 *
 * The live downlink vocabulary is `streamFrames`: `session/follow` and
 * `session/control` are the logical streams Aeroric opens over the
 * `/api/remote.mux` WebSocket, and `remoteDownlink` is that socket's own
 * `$events` frame set. DSH-14 retired the `/api/events.mux` +
 * `/api/events.host` firehose outright — there is no fail-soft mux/host table
 * here any more, and the retired names are asserted-against in
 * `protocol_inventory.rs` so they cannot come back.
 *
 * Desktop-host handshake is independently versioned
 * (`DESKTOP_HOST_PROTOCOL_VERSION = 3` in `apps/desktop-host/src/wire.ts`).
 * Aeroric starts `dsh web` itself and is not on that wire; recorded here so
 * the next drift pass does not rediscover it as an unexplained bump.
 */

export const DSH_PROTOCOL_SNAPSHOT = {
  sourceCommit: "c291e7961a515f6d7af9304e7fd1d257929aef26",
  packageVersion: "0.1.5-rc.2",
  protocolVersion: 2,
  rpcMethods: [
    "session.list",
    "session.search",
    "session.create",
    "session.selectModel",
    "session.modelCatalog",
    "session.canOpenWorkspacePath",
    "session.openWorkspacePath",
    "session.rename",
    "session.fork",
    "session.prompt",
    "session.attachment",
    "session.updateQueue",
    "session.cancel",
    "session.page",
    "session.follow",
    "session.control",
    "subagents.list",
    "subagents.prompt",
    "subagents.interruptByParent",
    "directoryPicker.pick",
    "directoryPicker.list",
    "directoryPicker.createDirectory",
    "workspace.create",
    "workspace.rename",
    "workspace.delete",
    "workspace.insertBefore",
    "workspace.insertSessionBefore",
    "workspace.archiveSession",
    "workspace.follow",
    "workspaceFiles.list",
    "workspaceFiles.read",
    "workspaceFiles.readAll",
    "workspaceFiles.readBytes",
    "workspaceFiles.readRelated",
    "workspaceFiles.stat",
    "workspaceFiles.changes",
    "skills.list",
    "agentPresets.list",
    "agentPresets.select",
    "agentPresets.read",
    "agentPresets.copy",
    "agentPresets.deletePreset",
    "goals.create",
    "goals.edit",
    "goals.pause",
    "goals.resume",
    "goals.complete",
    "goals.clear",
    "goals.get",
    "settings.describe",
    "settings.openSettingsDocument",
    "settings.update",
    "settings.replace",
    "settings.mutate",
    "settings.canOpenAgentPresetDirectory",
    "settings.openAgentPresetDirectory",
    "credentials.describe",
    "credentials.set",
    "credentials.unset",
    "llm.listProviders",
    "llm.listConfigurableProviders",
    "llm.discoverModels",
  ],
  remoteMethods: [
    "session.list",
    "session.search",
    "session.create",
    "session.selectModel",
    "session.modelCatalog",
    "session.canOpenWorkspacePath",
    "session.openWorkspacePath",
    "session.rename",
    "session.fork",
    "session.prompt",
    "session.attachment",
    "session.updateQueue",
    "session.cancel",
    "session.page",
    "session.follow",
    "session.control",
    "subagents.list",
    "subagents.prompt",
    "subagents.interruptByParent",
    "directoryPicker.pick",
    "directoryPicker.list",
    "directoryPicker.createDirectory",
    "workspace.create",
    "workspace.rename",
    "workspace.delete",
    "workspace.insertBefore",
    "workspace.insertSessionBefore",
    "workspace.archiveSession",
    "workspace.follow",
    "workspaceFiles.list",
    "workspaceFiles.read",
    "workspaceFiles.readAll",
    "workspaceFiles.readBytes",
    "workspaceFiles.readRelated",
    "workspaceFiles.stat",
    "workspaceFiles.changes",
    "skills.list",
    "agentPresets.list",
    "agentPresets.select",
    "agentPresets.read",
    "agentPresets.copy",
    "agentPresets.deletePreset",
    "goals.create",
    "goals.edit",
    "goals.pause",
    "goals.resume",
    "goals.complete",
    "goals.clear",
    "goals.get",
    "settings.describe",
    "settings.openSettingsDocument",
    "settings.update",
    "settings.replace",
    "settings.mutate",
    "settings.canOpenAgentPresetDirectory",
    "settings.openAgentPresetDirectory",
    "credentials.describe",
    "credentials.set",
    "credentials.unset",
    "llm.listProviders",
    "llm.listConfigurableProviders",
    "llm.discoverModels",
    "commands.list",
    "commands.execute",
    "messageFeedback.list",
    "messageFeedback.put",
    "messageFeedback.delete",
    "pluginInventory.list",
    "dynamicCordisRunner.undefineFromPanel",
    "dynamicCordisRunner.runHostHalf",
    "dynamicCordisRunner.getClientCode",
    "dynamicCordisRunner.resolveRequestRun",
    "dynamicCordisRunner.settleUserRun",
    "dynamicCordisRunner.stopFromPanel",
    "dynamicCordisRunner.syncInspectManifest",
    "dynamicCordisRunner.resolveInspectQuery",
    "dynamicCordisRunner.inventory",
    "dynamicCordisRunner.reportRenderFailure",
    "dynamicCordisRunner.reportClientGuardFailure",
    "dynamicCordisRunner.invoke",
    "fileReferences.list",
    "sessionReferenceResolver.candidates",
    "fileUploads.upload",
    "sessionFeedback.record",
    "agentTeams.createTask",
    "agentTeams.updateTask",
    "agentTeams.view",
  ],
  remoteEvents: [
    { event: "agent-preset/selected", mode: "emit" },
    { event: "approval/request", mode: "waterfall" },
    { event: "api-session/activity", mode: "emit" },
    { event: "api-session/added", mode: "emit" },
    { event: "api-session/error", mode: "emit" },
    { event: "api-session/removed", mode: "emit" },
    { event: "api-session/status", mode: "emit" },
    { event: "commands/change", mode: "emit" },
    { event: "credentials/reference-updated", mode: "emit" },
    { event: "goal/activation-changed", mode: "emit" },
    { event: "cordis/request-run", mode: "emit" },
    { event: "cordis/request-run-resolved", mode: "emit" },
    { event: "cordis/dynamic-package", mode: "emit" },
    { event: "cordis/dynamic-retract", mode: "emit" },
    { event: "cordis/inspect-query", mode: "emit" },
    { event: "cordis/inspect-query-resolved", mode: "emit" },
    { event: "llm/adapters-updated", mode: "emit" },
    { event: "settings/document-updated", mode: "emit" },
    { event: "user-questions/request", mode: "waterfall" },
  ],
  streamFrames: {
    sessionFollow: ["snapshot", "event", "assistant-stream"],
    sessionControl: ["baseline", "queue", "jobs", "projection"],
    remoteDownlink: ["ready", "emit", "waterfall", "cancel"],
  },
  features: {
    structuredHistory: true,
    reasoning: true,
    markdownAndMath: true,
    imageAttachments: true,
    toolPresentation: true,
    trajectory: true,
    stats: true,
    deliverables: true,
    feedback: true,
    schedule: true,
    workflow: true,
    nestedSubagents: true,
    queueAndSteering: true,
    permissions: true,
    plansGoalsTodos: true,
    pluginsAndPresets: true,
    localWslSshTransport: true,
  },
} as const;

export type DshProtocolSnapshot = typeof DSH_PROTOCOL_SNAPSHOT;
export type DshRemoteEventMode = (typeof DSH_PROTOCOL_SNAPSHOT.remoteEvents)[number]["mode"];

